/**
 * CFB 27 archetype names, keyed by the save's internal enum.
 *
 * GENERATED by scripts/extract-archetypes.ts — do not edit by hand.
 *
 * The save carries Madden-lineage identifiers (`QB_FieldGeneral`) while the
 * game shows its own labels (`Pocket Passer`). Those labels come from the ARCH
 * table of an FTC container in the game's Frostbite bundles, addressed by the
 * PlayerType enum's numeric value, so this mapping is derived rather than
 * guessed. Anything unmapped falls back to a readable form of the enum.
 */
export const ARCHETYPE_LABELS: Record<string, string> = {
  // C
  C_Agile: "Agile",
  C_PassProtector: "Pass Protector",
  C_Power: "Raw Strength",
  C_WellRounded: "Well Rounded",

  // CB
  CB_HybridCorner: "Field",
  CB_MantoMan: "Bump and Run",
  CB_Slot: "Boundary",
  CB_Zone: "Zone",

  // DT
  DT_NoseTackle: "Gap Specialist",
  DT_PowerRusher: "Power Rusher",
  DT_PurePower: "Pure Power",
  DT_SpeedRusher: "Speed Rusher",

  // EDGE
  DE_PowerRusher: "Power Rusher",
  DE_PurePower: "Pure Power",
  DE_RunStopper: "Edge Setter",
  DE_SmallerSpeedRusher: "Speed Rusher",

  // FB
  FB_Blocking: "Blocking",
  FB_Utility: "Utility",

  // G
  G_Agile: "Agile",
  G_PassProtector: "Pass Protector",
  G_Power: "Raw Strength",
  G_WellRounded: "Well Rounded",

  // GAD
  GAD_Gadget: "Gadget",

  // HB
  HB_ElusiveBack: "East/West Playmaker",
  HB_ElusivePower: "Elusive Bruiser",
  HB_ElusiveReceiving: "East/West Receiver",
  HB_PowerBack: "Contact Seeker",
  HB_PowerBlocking: "North/South Blocker",
  HB_PowerReceiving: "North/South Receiver",
  HB_ReceivingBack: "Backfield Threat",

  // KP
  KP_Accurate: "Accurate",
  KP_Power: "Power",

  // KR
  KR_Balanced: "Balanced",

  // LS
  LS_Accurate: "Accurate",
  LS_Power: "Power",

  // MIKE
  MLB_FieldGeneral: "Signal Caller",
  MLB_PassCoverage: "Lurker",
  MLB_RunStopper: "Thumper",

  // OLB
  OLB_PassCoverage: "Lurker",
  OLB_PowerRusher: "Signal Caller",
  OLB_RunStopper: "Thumper",

  // OT
  OT_Agile: "Agile",
  OT_PassProtector: "Pass Protector",
  OT_Power: "Raw Strength",
  OT_WellRounded: "Well Rounded",

  // PR
  PR_Balanced: "Balanced",

  // QB
  QB_FieldGeneral: "Pocket Passer",
  QB_Improviser: "Backfield Creator",
  QB_PureScrambler: "Pure Runner",
  QB_Scrambler: "Dual Threat",
  QB_StrongArm: "Strong Arm",

  // S
  S_Hybrid: "Hybrid",
  S_RunSupport: "Box Specialist",
  S_Zone: "Coverage Specialist",

  // TE
  TE_Blocking: "Pure Blocker",
  TE_PhysicalRouteRunner: "Physical Route Runner",
  TE_Possession: "Pure Possession",
  TE_PossessionBlocking: "Gritty Possession",
  TE_VerticalThreat: "Vertical Threat",

  // WR
  WR_DeepThreat: "Speedster",
  WR_GadgetReceiver: "Gadget",
  WR_Physical: "Contested Specialist",
  WR_PhysicalBlocker: "Gritty Possession",
  WR_PhysicalRouteRunner: "Physical Route Runner",
  WR_Playmaker: "Route Artist",
  WR_ShiftyRouteRunner: "Elusive Route Runner",
  WR_Slot: "Slot",
};
