/**
 * The game's coach talent trees: the head coach's 13 subtrees (coordinators
 * use the first 11), every node with its name, description, cost, screen
 * position, parent/children links and branch title, each subtree's
 * archetype-node prerequisite, and the enums' display names.
 *
 * GENERATED by scripts/extract-coach-talents.ts — do not edit by hand.
 *
 * Slot i is the coach's TalentSubTreeStatus[i]; node index N is that row's
 * TalentStatusN. Node 0 is the archetype (gate) node; every other node has
 * exactly one parent and becomes purchasable when the parent is owned.
 * Archetype value 1 is "Schemer" in the save enum but "Tactician" on screen —
 * map by value.
 */
export interface CoachTalentNode {
  index: number;
  name: string;
  desc: string;
  /** Coach points the game charges. */
  cost: number;
  /** Screen row (0 = the archetype node) and column. */
  level: number;
  column: number;
  parent: number | null;
  children: number[];
  /** Branch heading the game shows on a level-1 node, when it has one. */
  branch: string | null;
}

export interface CoachTalentSubTree {
  slot: number;
  name: string;
  desc: string;
  type: 'Base' | 'Hybrid' | 'Specialty';
  /** CoachTalentArcheType value this subtree represents. */
  archetype: number;
  canBeDominant: boolean;
  /** What unlocks the archetype node in-game (the game evaluates it natively). */
  prereq: { title: string; desc: string; minLevel: number; spendPoints: number } | null;
  nodes: CoachTalentNode[];
}

/** CoachTalentArcheType value → the name the game shows. */
export const COACH_ARCHETYPE_NAMES: Record<number, string> = {"0":"Motivator","1":"Tactician","2":"Recruiter","3":"Master Motivator","4":"Architect","5":"Scheme Guru","6":"Strategist","7":"Elite Recruiter","8":"Talent Developer","9":"Rainmaker","10":"Visionary","11":"Program Builder","12":"CEO"};

/** CoachBackstory value → the name the game shows (only these three are named). */
export const COACH_BACKSTORY_NAMES: Record<number, string> = {"0":"Motivator","1":"Strategist","2":"Team Builder"};

export const HEAD_COACH_TALENT_TREE: CoachTalentSubTree[] = [
  {
    slot: 0, name: "Motivator", desc: "Culture setter who is strong in player development", type: "Base", archetype: 0, canBeDominant: true,
    prereq: {"title":"Motivator Prerequisites","desc":"","minLevel":10,"spendPoints":0},
    nodes: [
      { index: 0, name: "Grow Together", desc: "7 Bonus XP whenever a player levels up", cost: 25, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Extra Gear - QB", desc: "QB's get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Hot Hand - QB", desc: "QB's stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Put in Work - QB", desc: "QB's get an off-season training boost", cost: 25, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Locked In - QB", desc: "QB's start the 4th quarter \"hot\" in close games.", cost: 30, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Extra Gear - RB", desc: "RB's get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "Hot Hand - RB/FB", desc: "RB/FB's stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Put in Work - RB/FB", desc: "RB/FB's get an off-season training boost", cost: 25, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Locked In - RB/FB", desc: "RB/FB's start the 4th quarter \"hot\" in close games", cost: 30, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Extra Gear - WR/TE", desc: "WR/TE's get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "Hot Hand - WR/TE", desc: "WR/TE's stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Put in Work - WR/TE", desc: "WR/TE's get an off-season training boost", cost: 25, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Locked In - WR/TE", desc: "WR/TE's start the 4th quarter \"hot\" in close games", cost: 30, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Extra Gear - OL", desc: "OL get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Hot Hand - OL", desc: "OL stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Put in Work - OL", desc: "OL get an off-season training boost", cost: 25, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Locked In - OL", desc: "OL start the 4th quarter \"hot\" in close games", cost: 30, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Extra Gear - DL", desc: "DL get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "Hot Hand - DL", desc: "DL stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Put in Work - DL", desc: "DL get an off-season training boost", cost: 25, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Locked In - DL", desc: "DL start the 4th quarter \"hot\" in close games", cost: 30, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Extra Gear - LB", desc: "LB's get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "Hot Hand - LB", desc: "LB's stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Put in Work - LB", desc: "LB's get an off-season training boost", cost: 25, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Locked In - LB", desc: "LB's start the 4th quarter \"hot\" in close games", cost: 30, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Extra Gear - DB", desc: "DB's get boosts to Toughness, Stamina, and Injury", cost: 15, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "Hot Hand - DB", desc: "DB's stay hot through timeouts, quarter change, & across games", cost: 20, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Put in Work - DB", desc: "DB's get an off-season training boost", cost: 25, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Locked In - DB", desc: "DB's start the 4th quarter \"hot\" in close games", cost: 30, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Extra Gear - K/P", desc: "K/P's get boosts to Toughness, Stamina, and Injury", cost: 10, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "Hot Hand - K/P", desc: "K/P's stay hot through timeouts, quarter change, & across games", cost: 10, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Put in Work - K/P", desc: "K/P's get an off-season training boost", cost: 15, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Locked In - K/P", desc: "K/P's start the 4th quarter \"hot\" in close games", cost: 15, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 1, name: "Tactician", desc: "Puts players in position to succeed on gameday", type: "Base", archetype: 1, canBeDominant: true,
    prereq: {"title":"Tactitian Prerequisites","desc":"","minLevel":10,"spendPoints":0},
    nodes: [
      { index: 0, name: "Winner", desc: "450 Bonus XP for each win", cost: 25, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Mobile QB Ratings Boost", desc: "Boosts to Throw on the Run and Change of Direction", cost: 20, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Passing QB Ratings Boost", desc: "Boosts Throw Under Pressure and Break Sack", cost: 20, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Mobile QB Ratings Boost 2", desc: "Boosts to Spin, Juke, and BC Vision", cost: 20, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Passing QB Ratings Boost 2", desc: "Boosts to Short and Medium Accuracy", cost: 20, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "RB/FB Ratings Boost", desc: "Boosts to Pass Block and Run Block", cost: 20, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "RB/FB Ratings Boost 2", desc: "Boosts to Trucking and Break Tackle", cost: 20, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "RB/FB Ratings Boost 3", desc: "Boosts to Spin, Juke, and BC Vision", cost: 20, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "RB/FB Ratings Boost 4", desc: "Boosts to Catch and Short Route", cost: 20, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "WR/TE Ratings Boost", desc: "Boosts to Run Block Power and Run Block Finesse", cost: 20, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "WR/TE Ratings Boost 2", desc: "Boosts to Juke and Spin", cost: 20, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "WR/TE Ratings Boost 3", desc: "Boosts to Short Route and Medium Route", cost: 20, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "WR/TE Ratings Boost 4", desc: "Boosts to Catch and Catch in Traffic", cost: 20, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Pass Block OL Ratings Boost", desc: "Boosts to Pass Block and Impact Block", cost: 20, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Run Block OL Ratings Boost", desc: "Boosts to Run Block and Lead Block", cost: 20, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Finesse OL Ratings Boost", desc: "Boosts to Run Block Finesse and Pass Block Finesse", cost: 20, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Power OL Ratings Boost", desc: "Boosts to Pass Block Power and Run Block Power", cost: 20, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "DL Ratings Boost", desc: "Boosts to Change of Direction and Pursuit", cost: 20, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "DL Ratings Boost 2", desc: "Boosts to Finesse Move and Block Shedding", cost: 20, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "DL Ratings Boost 3", desc: "Boosts to Power Move and Hit Power", cost: 20, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "DL Ratings Boost 4", desc: "Boosts to Tackle and Play Recognition", cost: 20, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "LB Ratings Boost", desc: "Boosts to Finesse Move and Block Shedding", cost: 20, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "LB Ratings Boost 2", desc: "Boosts to Pursuit and Play Recognition", cost: 20, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "LB Ratings Boost 3", desc: "Boosts to Man Coverage and Zone Coverage", cost: 20, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "LB Ratings Boost 4", desc: "Boosts to Tackle and Hit Power", cost: 20, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "DB Ratings Boost 1", desc: "Boosts to Spin, Juke, and BC Vision", cost: 20, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "DB Ratings Boost 2", desc: "Boosts to Catch and Jumping", cost: 20, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "DB Ratings Boost 3", desc: "Boosts to Man Coverage and Pursuit", cost: 20, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "DB Ratings Boost 4", desc: "Boosts to Zone Coverage and Play Recognition", cost: 20, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "K/P Rating Boost 1", desc: "Boost to kick accuracy", cost: 20, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "K/P Rating Boost 2", desc: "Extra boost to kick accuracy", cost: 20, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "K/P Rating Boost 3", desc: "Boost to kick power", cost: 20, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "K/P Rating Boost 4", desc: "Extra Boost to kick power", cost: 20, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 2, name: "Recruiter", desc: "Good at talent acquisition", type: "Base", archetype: 2, canBeDominant: true,
    prereq: {"title":"Recruiter Prerequisites","desc":"","minLevel":10,"spendPoints":0},
    nodes: [
      { index: 0, name: "Firm Handshakes", desc: "100 Bonus XP for signing a recruit", cost: 25, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Advanced Look - QB", desc: "Quarterbacks take less time to fully scout", cost: 15, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Persuasive Personality - QB", desc: "Increased chance to sway quarterbacks", cost: 20, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Magnetic Personality - QB", desc: "Increased starting interest from QB's", cost: 25, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Portal King - QB", desc: "Quarterback transfers are more interested", cost: 30, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Advanced Look - RB", desc: "Running backs take less time to fully scout", cost: 15, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "Persuasive Personality - RB", desc: "Increased chance to sway runningbacks", cost: 20, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Magnetic Personality - RB", desc: "Increased starting interest from RB's", cost: 25, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Portal King - RB", desc: "Running back transfers are more interested", cost: 30, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Advanced Look - WR/TE", desc: "WR/TE's take less time to fully scout", cost: 15, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "Persuasive Personality - WR/TE", desc: "Increased chance to sway WR and TE's", cost: 20, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Magnetic Personality - WR/TE", desc: "Increased starting interest from WR/TE's", cost: 25, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Portal King - WR/TE", desc: "WR/TE transfers are more interested", cost: 30, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Advanced Look - OL", desc: "OL takes less time to fully scout", cost: 15, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Persuasive Personality - OL", desc: "Increased chance to sway offensive linemen", cost: 20, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Magnetic Personality - OL", desc: "Increased starting interest from OL", cost: 25, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Portal King - OL", desc: "Offensive line transfers are more interested", cost: 30, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Advanced Look - DL", desc: "DL's take less time to fully scout", cost: 15, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "Persuasive Personality - DL", desc: "Increased chance to sway defensive linemen", cost: 20, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Magnetic Personality - DL", desc: "Increased starting interest from DL", cost: 25, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Portal King - DL", desc: "Defensive line transfers are more interested", cost: 30, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Advanced Look - LB", desc: "Linebackers take less time to fully scout", cost: 15, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "Persuasive Personality - LB", desc: "Increased chance to sway linebackers", cost: 20, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Magnetic Personality - LB", desc: "Increased starting interest from LB's", cost: 25, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Portal King - LB", desc: "Linebacker transfers are more interested", cost: 30, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Advanced Look - DB", desc: "Defensive backs take less time to fully scout", cost: 15, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "Persuasive Personality - DB", desc: "Increased chance to sway defensive backs", cost: 20, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Magnetic Personality - DB", desc: "Increased starting interest from DB's", cost: 25, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Portal King - DB", desc: "Defensive back transfers are more interested", cost: 30, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Advanced Look - K/P", desc: "Kickers & Punters take less time to fully scout", cost: 10, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "Persuasive Personality - K/P", desc: "Increased chance to sway kickers and punters", cost: 10, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Magnetic Personality - K/P", desc: "Increased starting interest from Kickers & Punters", cost: 15, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Portal King - K/P", desc: "K/P transfers are more interested", cost: 15, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 3, name: "Master Motivator", desc: "Can get anyone to run through a brick wall", type: "Base", archetype: 3, canBeDominant: true,
    prereq: {"title":"Master Motivator Prerequisites","desc":"Have 5 Players Drafted","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "Let's Grow", desc: "15 Bonus XP whenever a player levels up", cost: 15, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Quick Recovery - QB", desc: "QB's recover wear and tear damage faster", cost: 25, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Icy Veins - QB", desc: "Quarterbacks start games with a composure boost", cost: 30, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Family Atmosphere - QB", desc: "Quarterbacks are less likely to transfer", cost: 35, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Everybody Eats - QB", desc: "Increase all XP gains for Quarterbacks", cost: 40, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Quick Recovery - RB", desc: "RB's recover wear and tear damage faster", cost: 25, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "Icy Veins - RB", desc: "Running backs start games with a composure boost", cost: 30, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Family Atmosphere - RB", desc: "Running backs are less likely to transfer", cost: 35, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Everybody Eats - RB", desc: "Increase all XP gains for Running backs", cost: 40, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Quick Recovery - WR/TE", desc: "WR/TE's recover wear and tear damage faster", cost: 25, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "Icy Veins- WR/TE", desc: "WR/TE's start games with a composure boost", cost: 30, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Family Atmosphere - WR/TE", desc: "Wide Receivers and Tight Ends are less likely to transfer", cost: 35, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Everybody Eats - WR/TE", desc: "Increase all XP gains for Wide Receivers and Tight Ends", cost: 40, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Quick Recovery - OL", desc: "OL recover wear and tear damage faster", cost: 25, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Icy Veins - OL", desc: "Offensive linemen start games with a composure boost", cost: 30, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Family Atmosphere - OL", desc: "Offensive linemen are less likely to transfer", cost: 35, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Everybody Eats - OL", desc: "Increase all XP gains for Offensive linemen", cost: 40, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Quick Recovery - DL", desc: "DL recover wear and tear damage faster", cost: 25, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "Icy Veins - DL", desc: "Defensive linemen start games with a composure boost", cost: 30, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Family Atmosphere - DL", desc: "Defensive linemen are less likely to transfer", cost: 35, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Everybody Eats - DL", desc: "Increase all XP gains for Defensive linemen", cost: 40, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Quick Recovery - LB", desc: "LB's recover wear and tear damage faster", cost: 25, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "Icy Veins - LB", desc: "Linerbackers start games with a composure boost", cost: 30, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Family Atmosphere - LB", desc: "Linebackers are less likely to transfer", cost: 35, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Everybody Eats - LB", desc: "Increase all XP gains for Linebackers", cost: 40, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Quick Recovery - DB", desc: "DB's recover wear and tear damage faster", cost: 25, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "Icy Veins - DB", desc: "Defensive backs start games with a composure boost", cost: 30, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Family Atmosphere - DB", desc: "Defensive backs are less likely to transfer", cost: 35, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Everybody Eats - DB", desc: "Increase all XP gains for Defensive backs", cost: 40, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Quick Recovery - K/P", desc: "K/P's recover wear and tear damage faster", cost: 15, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "Icy Veins - K/P", desc: "K/P's start games with a composure boost", cost: 15, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Family Atmosphere - K/P", desc: "Kickers and Punters are less likely to transfer", cost: 20, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Everybody Eats - K/P", desc: "Increase all XP gains for Kickers and Punters", cost: 20, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 4, name: "Architect", desc: "Master at getting the most out of their players within a scheme", type: "Hybrid", archetype: 4, canBeDominant: true,
    prereq: {"title":"Architect Prerequisites","desc":"Win 4 Rivalry Games","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "Max Gains", desc: "400 Bonus XP when a player maxes a skill group", cost: 15, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Can't Stop, Won't Stop - QB", desc: "QB's earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Star Maker - QB", desc: "Starting Quarterback will gain XP faster", cost: 30, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Limitless - QB", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Put a Ring on It - QB", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Can't Stop, Won't Stop - RB", desc: "RB's earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "Star Maker - RB", desc: "Starting Running backs will gain XP faster", cost: 30, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Limitless - RB", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Put a Ring on It - RB", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Can't Stop, Won't Stop - WR/TE", desc: "WR/TE's earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "Star Maker - WR/TE", desc: "Starting WR and TE's will gain XP faster", cost: 30, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Limitless- WR/TE", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Put a Ring on It - WR/TE", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Can't Stop, Won't Stop - OL", desc: "OL earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Star Maker - OL", desc: "Starting Offensive Linemen will gain XP faster", cost: 30, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Limitless - OL", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Put a Ring on It - OL", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Can't Stop, Won't Stop - DL", desc: "DL earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "Star Maker - DL", desc: "Starting Defensive linemen will gain XP faster", cost: 30, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Limitless - DL", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Put a Ring on It - DL", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Can't Stop, Won't Stop - LB", desc: "LB's earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "Star Maker - LB", desc: "Starting Linebackers will gain XP faster", cost: 30, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Limitless - LB", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Put a Ring on It- LB", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Can't Stop, Won't Stop - DB", desc: "DB's earn an XP bonus for every three game win streak", cost: 25, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "Star Maker - DB", desc: "Starting Defensive backs will gain XP faster", cost: 30, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Limitless - DB", desc: "Chance to increase a random skill cap when leveling up", cost: 35, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Put a Ring on It - DB", desc: "Chance to increase best skill cap with a Conference or National title", cost: 40, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Can't Stop, Won't Stop - K/P", desc: "K/P's earn an XP bonus for every three game win streak", cost: 15, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "Star Maker - K/P", desc: "Starting Kicker and Punter will gain XP faster", cost: 15, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Limitless - K/P", desc: "Chance to increase a random skill cap when leveling up", cost: 20, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Put a Ring on It - K/P", desc: "Chance to increase best skill cap with a Conference or National title", cost: 20, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 5, name: "Scheme Guru", desc: "A master of the chess game", type: "Specialty", archetype: 5, canBeDominant: true,
    prereq: {"title":"Scheme Guru Prerequisites","desc":"Win 8 Top 25 Games","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "Winners Win", desc: "900 Bonus XP for each win", cost: 15, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Battery Pack", desc: "Offensive players fatigue slower in hurry up", cost: 30, level: 1, column: 0, parent: 0, children: [2], branch: "Fast Tempo Offense" },
      { index: 2, name: "Caught Napping", desc: "Increased delay to defenders looking to the sideline at the snap", cost: 30, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "On Their Heels", desc: "Team Composure boost for 1st downs gained running hurry up", cost: 30, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Tipped Your Hand", desc: "Chance to see the defense's coverage shell in hurry up", cost: 30, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Take what's there", desc: "Increased catch ability for passes 10 yards or less", cost: 30, level: 1, column: 1, parent: 0, children: [6], branch: "Pass Game Offense" },
      { index: 6, name: "Chew Up Yards", desc: "Increased catch ability for passes up to 20 yards downfield", cost: 30, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Stretch the FIeld", desc: "Increased catch ability for passes anywhere on the field", cost: 30, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "We See You", desc: "Chance for Post Snap Blitz Detection", cost: 30, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Wear 'Em Down", desc: "DL takes a fatigue hit for every 4+ yard rush", cost: 30, level: 1, column: 2, parent: 0, children: [10], branch: "Ground & Pound Offense" },
      { index: 10, name: "Demoralizing", desc: "DL & LB's take a fatigue hit for every 4+ yard rush", cost: 30, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Keep Blocks Longer", desc: "Reduces defender ability to disengage from run blocks", cost: 30, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "To the Whistle", desc: "Reduces defender ability to shed run blocks", cost: 30, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Hater Blockers", desc: "Slight reduction in crowd noise impact on the road", cost: 30, level: 1, column: 3, parent: 0, children: [14], branch: "Discipline - Offense" },
      { index: 14, name: "Teflon", desc: "Significant reduction of crowd noise impact on the road", cost: 30, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Polished", desc: "Offensive players will commit slightly fewer penalties", cost: 30, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Clean Sheet Offense", desc: "Offensive players will commit significantly fewer penalties", cost: 30, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Gas Tank", desc: "Defenders fatigue at a slower rate", cost: 30, level: 1, column: 4, parent: 0, children: [18], branch: "Fast Tempo Defense" },
      { index: 18, name: "Not So Fast", desc: "Reduced delay for defenders looking to the sideline at the snap", cost: 30, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Cardio Kings", desc: "DL maintain their shed ability vs hurry up offenses", cost: 30, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Camouflaged Coverage", desc: "Decrease offense's chance to see coverage shell in hurry up", cost: 30, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Puncher's chance", desc: "Increased knockout chance on passes 10 yards or less", cost: 30, level: 1, column: 5, parent: 0, children: [22], branch: "Pass Game Defense" },
      { index: 22, name: "No Mid Here", desc: "Increased knockout chance for passes up to 20 yards downfield", cost: 30, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Nothing Deep", desc: "Increased knockout chance for passes anywhere on the field", cost: 30, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Master of Disguise", desc: "Chance for protection from post snap blitz detection", cost: 30, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Keep 'Em Coming", desc: "DL fatigue slower on run plays", cost: 30, level: 1, column: 6, parent: 0, children: [26], branch: "Ground & Pound Defense" },
      { index: 26, name: "Fresh Legs", desc: "DL & LB's fatigue slower on run plays", cost: 30, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Hands Off", desc: "Increase ability to disengage on run plays", cost: 30, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "He Shed", desc: "Decrease the time between block shed attempts", cost: 30, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Unfriendly Confines", desc: "Slightly increased effects from crowd noise at home", cost: 30, level: 1, column: 7, parent: 0, children: [30], branch: "Discipline - Defense" },
      { index: 30, name: "Too Loud???", desc: "Significant increase to effects of crowd noise at home", cost: 30, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "No Free Yards", desc: "Defenders will commit slightly fewer penalties", cost: 30, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Clean Sheet Defense", desc: "Defenders will commit significantly fewer penalties", cost: 30, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 6, name: "Strategist", desc: "Perfect blend of X's and O's and talent acquisition", type: "Hybrid", archetype: 6, canBeDominant: true,
    prereq: {"title":"Strategist Prerequisites","desc":"Win Four Bowl Games","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "Show Don't Tell", desc: "1,000 Bonus XP for each prospect visiting for a win", cost: 15, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Making Friends - QB", desc: "Boost to complimentary visits for Quarterbacks", cost: 25, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Hospitality - QB", desc: "Visits have a bigger impact on Quarterback prospects", cost: 30, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Lower the Bar - QB", desc: "QB's have a lower dealbreaker threshold", cost: 35, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Mind Reader - QB", desc: "Increased chance to learn devtrait of QB's while scouting", cost: 40, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Making Friends - RB", desc: "Boost to complimentary visits for Running backs", cost: 25, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "Hospitality - RB", desc: "Visits have a bigger impact on Running back prospects", cost: 30, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Lower the Bar - RB", desc: "RB's have a lower dealbreaker threshold", cost: 35, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Mind Reader - RB", desc: "Increased chance to learn devtrait of RB's while scouting", cost: 40, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Making Friends - WR/TE", desc: "Boost to complimentary visits for WR/TE's", cost: 25, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "Hospitality - WR/TE", desc: "Visits have a bigger impact on WR/TE prospects", cost: 30, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Lower the Bar - WR/TE", desc: "WR/TE have a lower dealbreaker threshold", cost: 35, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Mind Reader - WR/TE", desc: "Increased chance to learn devtrait of WR/TE's while scouting", cost: 40, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Making Friends - OL", desc: "Boost to complimentary visits for Offensive linemen", cost: 25, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Hospitality - OL", desc: "Visits have a bigger impact on Offensive linemen prospects", cost: 30, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Lower the Bar - OL", desc: "OL have a lower dealbreaker threshold", cost: 35, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Mind Reader - OL", desc: "Increased chance to learn devtrait of OL while scouting", cost: 40, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Making Friends - DL", desc: "Boost to complimentary visits for Defensive linemen", cost: 25, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "Hospitality - DL", desc: "Visits have a bigger impact on Defensive linemen prospects", cost: 30, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Lower the Bar - DL", desc: "DL's have a lower dealbreaker threshold", cost: 35, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Mind Reader - DL", desc: "Increased chance to learn devtrait of DL while scouting", cost: 40, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Making Friends - LB", desc: "Boost to complimentary visits for Linebackers", cost: 25, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "Hospitality - LB", desc: "Visits have a bigger impact on Linebacker prospects", cost: 30, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Lower the Bar - LB", desc: "LB's have a lower dealbreaker threshold", cost: 35, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Mind Reader - LB", desc: "Increased chance to learn devtrait of LB's while scouting", cost: 40, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Making Friends - DB", desc: "Boost to complimentary visits for Defensive backs", cost: 25, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "Hospitality - DB", desc: "Visits have a bigger impact on Defensive back prospects", cost: 30, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Lower the Bar - DB", desc: "DB's have a lower dealbreaker threshold", cost: 35, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Mind Reader - DB", desc: "Increased chance to learn devtrait of DB's while scouting", cost: 40, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Making Friends - K/P", desc: "Boost to complimentary visits for K/P", cost: 15, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "Hospitality - K/P", desc: "Visits have a bigger impact on K/P prospects", cost: 15, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Lower the Bar - K/P", desc: "K/P's have a lower dealbreaker threshold", cost: 20, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Mind Reader - K/P", desc: "Increased chance to learn devtrait of K/P's while scouting", cost: 20, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 7, name: "Elite Recruiter", desc: "The best of the best at talent acquisition", type: "Base", archetype: 7, canBeDominant: true,
    prereq: {"title":"Sign a Top 5 Recruiting Class","desc":"Sign Two Top 5 Recruiting Classes","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "Firmer Handshakes", desc: "200 Bonus XP for signing a recruit", cost: 15, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "Ideal Situation - QB", desc: "Boost to ideal pitch grades for Quarterbacks", cost: 25, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "Upsell- QB", desc: "My School grades have a larger impact on QB's", cost: 30, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Most Influential - QB", desc: "Recruiting actions have bigger impacts on QB's", cost: 35, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Always Be Crootin' - QB", desc: "Increase weekly recruiting hours for QB's", cost: 40, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "Ideal Situation - RB", desc: "Boost to ideal pitch grades for Running backs", cost: 25, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "Upsell - RB", desc: "My School grades have a larger impact on RB's", cost: 30, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Most Influential - RB", desc: "Recruiting actions give a bonus to RB's", cost: 35, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Always Be Crootin' - RB", desc: "Increase weekly recruiting hours for RB's", cost: 40, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "Ideal Situation - WR/TE", desc: "Boost to ideal pitch grades for WR/TE's", cost: 25, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "Upsell - WR/TE", desc: "My School grades have a larger impact on WR/TE's", cost: 30, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Most Influential - WR/TE", desc: "Recruiting actions give a bonus to WR/TE's", cost: 35, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Always Be Crootin' - WR/TE", desc: "Increase weekly recruiting hours for WR/TE's", cost: 40, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Ideal Situation - OL", desc: "Boost to ideal pitch grades for Offensive linemen", cost: 25, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "Upsell - OL", desc: "My School grades have a larger impact on OL", cost: 30, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Most Influential - OL", desc: "Recruiting actions give a bonus to OL", cost: 35, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Always Be Crootin' - OL", desc: "Increase weekly recruiting hours for OL", cost: 40, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "Ideal Situation - DL", desc: "Boost to ideal pitch grades for Defensive lineman", cost: 25, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "Upsell - DL", desc: "My School grades have a larger impact on DL's", cost: 30, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Most Influential - DL", desc: "Recruiting actions give a bonus to DL's", cost: 35, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Always Be Crootin' - DL", desc: "Increase weekly recruiting hours for DL", cost: 40, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "Ideal Situation - LB", desc: "Boost to ideal pitch grades for Linebackers", cost: 25, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "Upsell - LB", desc: "My School grades have a larger impact on LB's", cost: 30, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Most Influential - LB", desc: "Recruiting actions give a bonus to LB's", cost: 35, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Always Be Crootin' - LB", desc: "Increase weekly recruiting hours for LB's", cost: 40, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "Ideal Situation - DB", desc: "Boost to ideal pitch grades for Defensive backs", cost: 25, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "Upsell - DB", desc: "My School grades have a larger impact on DB's", cost: 30, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Most Influential - DB", desc: "Recruiting actions give a bonus to DB's", cost: 35, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Always Be Crootin' - DB", desc: "Increase weekly recruiting hours for DB's", cost: 40, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "Ideal Situation - K/P", desc: "Boost to ideal pitch grades for Kickers & Punters", cost: 15, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "Upsell - K/P", desc: "My School grades have a larger impact on K/P's", cost: 15, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Most Influential - K/P", desc: "Recruiting actions give a bonus to K/P", cost: 20, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Always Be Crootin' - K/P", desc: "Increase weekly recruiting hours for K/P's", cost: 20, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 8, name: "Talent Developer", desc: "Great at acquiring and developing talent", type: "Hybrid", archetype: 8, canBeDominant: true,
    prereq: {"title":"Talent Developer Prerequisites","desc":"Two Players Drafted in the 1st Round","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "Draft Dividends", desc: "2,000 Bonus XP when a player is drafted", cost: 15, level: 0, column: 0, parent: null, children: [1, 5, 9, 13, 17, 21, 25, 29], branch: null },
      { index: 1, name: "FIeld Study - QB", desc: "Quarterbacks earn additional XP for in-game goals", cost: 25, level: 1, column: 0, parent: 0, children: [2], branch: "Passing Game (QB)" },
      { index: 2, name: "QB Whisperer", desc: "Freshmen and Sophomore Quarterbacks progress faster", cost: 30, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Home Sweet Home - QB", desc: "Boost to pipeline bonus for Quarterbacks", cost: 35, level: 3, column: 0, parent: 2, children: [4], branch: null },
      { index: 4, name: "Pay it Forward - QB", desc: "Bonus XP for QB's when QB's are drafted", cost: 40, level: 4, column: 0, parent: 3, children: [], branch: null },
      { index: 5, name: "FIeld Study - RB", desc: "Running backs earn additonal XP for in-game goals", cost: 25, level: 1, column: 1, parent: 0, children: [6], branch: "Running Game (RB/FB)" },
      { index: 6, name: "RB Whisperer", desc: "Freshmen and Sophomore Running backs progress faster", cost: 30, level: 2, column: 2, parent: 5, children: [7], branch: null },
      { index: 7, name: "Home Sweet Home - RB", desc: "Boost to pipeline bonus for Running backs", cost: 35, level: 3, column: 1, parent: 6, children: [8], branch: null },
      { index: 8, name: "Pay it Forward - RB", desc: "Bonus XP for RB's when RB's are drafted", cost: 40, level: 4, column: 1, parent: 7, children: [], branch: null },
      { index: 9, name: "FIeld Study - WR/TE", desc: "WR/TE's earn additional XP for in-game goals", cost: 25, level: 1, column: 2, parent: 0, children: [10], branch: "Receiving Game (WR/TE)" },
      { index: 10, name: "WR/TE Whisperer", desc: "Freshmen and Sophomore WR and TE progress faster", cost: 30, level: 2, column: 2, parent: 9, children: [11], branch: null },
      { index: 11, name: "Home Sweet Home - WR/TE", desc: "Boost to pipeline bonus for WR/TE's", cost: 35, level: 3, column: 2, parent: 10, children: [12], branch: null },
      { index: 12, name: "Pay it Forward  - WR/TE", desc: "Bonus XP for WR/TE's when WR/TE's are drafted", cost: 40, level: 4, column: 2, parent: 11, children: [], branch: null },
      { index: 13, name: "Field Study - OL", desc: "Offensive linemen earn additional XP for in-game goals", cost: 25, level: 1, column: 3, parent: 0, children: [14], branch: "Blocking (OL)" },
      { index: 14, name: "OL Whisperer", desc: "Freshmen and Sophomore Offensive linemen progress faster", cost: 30, level: 2, column: 3, parent: 13, children: [15], branch: null },
      { index: 15, name: "Home Sweet Home - OL", desc: "Boost to pipeline bonus for Offensive linemen", cost: 35, level: 3, column: 3, parent: 14, children: [16], branch: null },
      { index: 16, name: "Pay it Forward - OL", desc: "Bonus XP for OL when OL are drafted", cost: 40, level: 4, column: 3, parent: 15, children: [], branch: null },
      { index: 17, name: "FIeld Study - DL", desc: "Defensive linemen earn additional XP for in-game goals", cost: 25, level: 1, column: 4, parent: 0, children: [18], branch: "Defensive Line (DL)" },
      { index: 18, name: "DL Whisperer", desc: "Freshmen and Sophomore Defensive linemen progress faster", cost: 30, level: 2, column: 4, parent: 17, children: [19], branch: null },
      { index: 19, name: "Home Sweet Home - DL", desc: "Boost to pipeline bonus for Defensive linemen", cost: 35, level: 3, column: 4, parent: 18, children: [20], branch: null },
      { index: 20, name: "Pay it Forward - DL", desc: "Bonus XP for DL's when DL's are drafted", cost: 40, level: 4, column: 4, parent: 19, children: [], branch: null },
      { index: 21, name: "FIeld Study - LB", desc: "Linebackers earn additional XP for in-game goals", cost: 25, level: 1, column: 5, parent: 0, children: [22], branch: "Linebackers (LB)" },
      { index: 22, name: "LB Whisperer", desc: "Freshmen and Sophomore Linebackers progress faster", cost: 30, level: 2, column: 5, parent: 21, children: [23], branch: null },
      { index: 23, name: "Home Sweet Home - LB", desc: "Boost to pipeline bonus for Linebackers", cost: 35, level: 3, column: 5, parent: 22, children: [24], branch: null },
      { index: 24, name: "Pay it Forward - LB", desc: "Bonus XP for LB's when LB's are drafted", cost: 40, level: 4, column: 5, parent: 23, children: [], branch: null },
      { index: 25, name: "FIeld Study - DB", desc: "Defensive backs earn additional XP for in-game goals", cost: 25, level: 1, column: 6, parent: 0, children: [26], branch: "Secondary (DB)" },
      { index: 26, name: "DB Whisperer", desc: "Freshmen and Sophomore Defensive backs progress faster", cost: 30, level: 2, column: 6, parent: 25, children: [27], branch: null },
      { index: 27, name: "Home Sweet Home - DB", desc: "Boost to pipeline bonus for Defensive backs", cost: 35, level: 3, column: 6, parent: 26, children: [28], branch: null },
      { index: 28, name: "Pay it Forward - DB", desc: "Bonus XP for DB's when DB's are drafted", cost: 40, level: 4, column: 6, parent: 27, children: [], branch: null },
      { index: 29, name: "FIeld Study - K/P", desc: "Kickers and Punters earn additional XP for in-game goals", cost: 15, level: 1, column: 7, parent: 0, children: [30], branch: "Specialists (K/P)" },
      { index: 30, name: "K/P Whisperer", desc: "Freshmen and Sophomore Kickers and Punters progress faster", cost: 15, level: 2, column: 7, parent: 29, children: [31], branch: null },
      { index: 31, name: "Home Sweet Home - K/P", desc: "Boost to pipeline bonus for Kickers & Punters", cost: 20, level: 3, column: 7, parent: 30, children: [32], branch: null },
      { index: 32, name: "Pay it Forward - K/P", desc: "Bonus XP for K/P's when K/P's are drafted", cost: 20, level: 4, column: 7, parent: 31, children: [], branch: null },
    ]
  },
  {
    slot: 9, name: "Rainmaker", desc: "Exclusively for MVP+ Members", type: "Specialty", archetype: 9, canBeDominant: false,
    prereq: {"title":"Rainmaker Prerequisites","desc":"Be an MVP+ Member","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "", desc: "---", cost: 0, level: 0, column: 0, parent: null, children: [1, 2, 3, 4], branch: null },
      { index: 1, name: "Deal Maker", desc: "Increased recruiting influence from NIL offers", cost: 15, level: 1, column: 0, parent: 0, children: [], branch: "Rainmaker" },
      { index: 2, name: "Budget Booster", desc: "Increased Dynasty Points from My School grades", cost: 15, level: 1, column: 1, parent: 0, children: [], branch: "Rainmaker" },
      { index: 3, name: "Staying Power", desc: "Increase NIL Offer impact on Risk of Leaving", cost: 15, level: 1, column: 2, parent: 0, children: [], branch: "Rainmaker" },
      { index: 4, name: "Contract Incentives", desc: "Increased Dynasty Points from AD Expectation Goals", cost: 15, level: 1, column: 3, parent: 0, children: [], branch: "Rainmaker" },
    ]
  },
  {
    slot: 10, name: "Visionary", desc: "Awarded for creating a Coach in Madden 27", type: "Base", archetype: 10, canBeDominant: false,
    prereq: {"title":"Visionary Prerequisites","desc":"Create a Coach in Madden NFL 27 Franchise Mode","minLevel":0,"spendPoints":0},
    nodes: [
      { index: 0, name: "", desc: "---", cost: 0, level: 0, column: 0, parent: null, children: [1, 2, 3, 4], branch: null },
      { index: 1, name: "Pro Pipeline", desc: "Increase player's NFL draft stock", cost: 15, level: 1, column: 0, parent: 0, children: [], branch: "Visionary" },
      { index: 2, name: "Practice Makes Perfect", desc: "Increased player progression from practice", cost: 15, level: 1, column: 1, parent: 0, children: [], branch: "Visionary" },
      { index: 3, name: "Hot Start", desc: "Increased chance of players starting Hot from practice", cost: 15, level: 1, column: 2, parent: 0, children: [], branch: "Visionary" },
      { index: 4, name: "Signing Bonus", desc: "Increased annual Coach Points award from your program", cost: 15, level: 1, column: 3, parent: 0, children: [], branch: "Visionary" },
    ]
  },
  {
    slot: 11, name: "Program Builder", desc: "Head Coach who can oversee everything", type: "Specialty", archetype: 11, canBeDominant: true,
    prereq: {"title":"Program Builder Prerequisites","desc":"Win 5 Playoff Games","minLevel":0,"spendPoints":300},
    nodes: [
      { index: 0, name: "Winning Together", desc: "75 Bonus XP when a school grade or prestige increases", cost: 70, level: 0, column: 0, parent: null, children: [1, 4, 7, 10, 13, 16, 19], branch: null },
      { index: 1, name: "Forever Home", desc: "Coordinators are less likely to leave in the coaching carousel", cost: 40, level: 1, column: 0, parent: 0, children: [2], branch: "Coaching Family" },
      { index: 2, name: "Deal Sweetener", desc: "Coordinators are more likely to accept your job offer", cost: 40, level: 2, column: 0, parent: 1, children: [3], branch: null },
      { index: 3, name: "Cream of the Crop", desc: "Increase coordinator interest in your job openings", cost: 40, level: 3, column: 0, parent: 2, children: [], branch: null },
      { index: 4, name: "Home Field Advantage", desc: "Increased HFA composure penalties for away team at home", cost: 40, level: 1, column: 1, parent: 0, children: [5], branch: "Set The Tone" },
      { index: 5, name: "Road Warriors", desc: "Protection from HFA composure penalties on road", cost: 40, level: 2, column: 1, parent: 4, children: [6], branch: null },
      { index: 6, name: "Not Intimidated", desc: "Increased/protection from HFA composure effects in rivalry games", cost: 40, level: 3, column: 1, parent: 5, children: [], branch: null },
      { index: 7, name: "Best Advice", desc: "3rd-7th round projected players are less likely to leave for the NFL", cost: 40, level: 1, column: 2, parent: 0, children: [8], branch: "Roster Retention" },
      { index: 8, name: "Let's Run It Back", desc: "2nd round projected players are less likely to leave for the NFL", cost: 40, level: 2, column: 2, parent: 7, children: [9], branch: null },
      { index: 9, name: "Delay Sunday", desc: "1st round projected players are less likely to leave for the NFL", cost: 40, level: 3, column: 2, parent: 8, children: [], branch: null },
      { index: 10, name: "Gift of Gab", desc: "Gain 3 additional persuade attempts per season", cost: 40, level: 1, column: 3, parent: 0, children: [11], branch: "High Integrity" },
      { index: 11, name: "Roster Retainer", desc: "Persuades have a higher success rate", cost: 40, level: 2, column: 3, parent: 10, children: [12], branch: null },
      { index: 12, name: "Full Refund", desc: "Successful Persuades refund the attempt", cost: 40, level: 3, column: 3, parent: 11, children: [], branch: null },
      { index: 13, name: "Smart Goals", desc: "Earn 25% more XP from all completed goals", cost: 40, level: 1, column: 4, parent: 0, children: [14], branch: "Inside Track" },
      { index: 14, name: "Portal Preview", desc: "Able to see other school's At Risk players in My School", cost: 40, level: 2, column: 4, parent: 13, children: [15], branch: null },
      { index: 15, name: "Friends & Family Discount", desc: "Archetypes are 50CP cheaper for each coach that owns that Archetype", cost: 40, level: 3, column: 4, parent: 14, children: [], branch: null },
      { index: 16, name: "Invest", desc: "Upgrade your school's best two pipelines by one tier", cost: 40, level: 1, column: 5, parent: 0, children: [17], branch: "Relationship Builder" },
      { index: 17, name: "Making Inroads", desc: "Upgrades your school's five best pipelines by one tier", cost: 40, level: 2, column: 5, parent: 16, children: [18], branch: null },
      { index: 18, name: "Share the Wealth", desc: "Upgrades your school's five worst pipelines by one tier", cost: 40, level: 3, column: 5, parent: 17, children: [], branch: null },
      { index: 19, name: "Giving Back", desc: "Boost to your Primary Pipeline", cost: 40, level: 1, column: 6, parent: 0, children: [20], branch: "Strong Roots" },
      { index: 20, name: "Household Name", desc: "Boost to starting interest for recruits from your Primary Pipeline", cost: 40, level: 2, column: 6, parent: 19, children: [21], branch: null },
      { index: 21, name: "Hometown Discount", desc: "Recruits from your Primary Pipeline gain extra influence boosts", cost: 40, level: 3, column: 6, parent: 20, children: [], branch: null },
    ]
  },
  {
    slot: 12, name: "CEO", desc: "Elite Head Coach who has won a National Title", type: "Specialty", archetype: 12, canBeDominant: true,
    prereq: {"title":"CEO Prerequisites","desc":"Win Two National Championships","minLevel":0,"spendPoints":500},
    nodes: [
      { index: 0, name: "Big Game Bonus", desc: "12,500 Bonus XP for Playoff wins", cost: 90, level: 0, column: 0, parent: null, children: [1, 2, 3, 4, 5, 6, 7, 8, 9], branch: null },
      { index: 1, name: "Gainz Getter", desc: "Increase the chance that a player upgrades their dev trait", cost: 40, level: 1, column: 0, parent: 0, children: [], branch: "CEO" },
      { index: 2, name: "Second Chance Keeper", desc: "Spend a second persuade on a player if the first fails", cost: 40, level: 1, column: 1, parent: 0, children: [], branch: "CEO" },
      { index: 3, name: "Lasting Impression", desc: "Gain additional interest for every 10 hours spent", cost: 40, level: 1, column: 2, parent: 0, children: [], branch: "CEO" },
      { index: 4, name: "More the Merrier", desc: "Increase the number of players who can visit in a week to 8", cost: 40, level: 1, column: 3, parent: 0, children: [], branch: "CEO" },
      { index: 5, name: "Gasoline", desc: "Players start Hot in top 5/rivalry/bowl/championship games", cost: 40, level: 1, column: 4, parent: 0, children: [], branch: "CEO" },
      { index: 6, name: "Last Dance", desc: "Bonus interest for every visit a player has taken before visiting you", cost: 40, level: 1, column: 5, parent: 0, children: [], branch: "CEO" },
      { index: 7, name: "Dream School", desc: "Chance at Instant commit when offering scholarship as their top school", cost: 40, level: 1, column: 6, parent: 0, children: [], branch: "CEO" },
      { index: 8, name: "Bundle Discount", desc: "Coach Abilities are 5CP less for every coach on your staff with that ability", cost: 40, level: 1, column: 7, parent: 0, children: [], branch: "CEO" },
      { index: 9, name: "Senior Superlatives", desc: "Increase all skill group caps by one for rising Seniors", cost: 40, level: 1, column: 8, parent: 0, children: [], branch: "CEO" },
    ]
  },
];

/** Coordinators run the same tree without the two head-coach specialties. */
export const COORDINATOR_TALENT_TREE: CoachTalentSubTree[] = HEAD_COACH_TALENT_TREE.slice(0, 11);

/** The tree for a save Position member ('HeadCoach' | 'OffensiveCoordinator' | 'DefensiveCoordinator'). */
export function coachTalentTree(position: string): CoachTalentSubTree[] {
  return position === 'HeadCoach' ? HEAD_COACH_TALENT_TREE : COORDINATOR_TALENT_TREE;
}
