/**
 * CFB 27 athletic facilities: the five building levels and the equipment
 * catalog, from the game's own tuning store (BuildingTeamUpgrade + Equipment).
 *
 * GENERATED by scripts/extract-facilities.ts — do not edit by hand.
 *
 * The save keeps the level in Team.FacilitiesLevel (0–4) and reserves the
 * level's renewal fee in FacilitiesRenewalCostReserved; owned equipment rows
 * (EquipmentTeamUpgradeStatus) reference items by the 32-bit asset id below.
 */
export interface FacilityLevel {
  level: number;
  name: string;
  desc: string;
  cost: number;
  renewCost: number;
  /** Equipment slots the level allows. */
  slotCap: number;
  /** The AthleticFacilitiesGrade band the level pins (best..worst, save member ids). */
  bestGrade: string;
  worstGrade: string;
  normalThreshold: number;
  plusThreshold: number;
}

export interface FacilityEquipment {
  /** 32-bit asset id as the save stores the TeamUpgrade ref (binary string). */
  assetId: string;
  name: string;
  desc: string;
  cost: number;
  tier: number;
  effect: string;
  value: number;
}

export const FACILITY_LEVELS: FacilityLevel[] = [
  {
    "level": 0,
    "name": "Basic Facility",
    "desc": "",
    "cost": 0,
    "renewCost": 0,
    "slotCap": 1,
    "bestGrade": "F",
    "worstGrade": "F",
    "normalThreshold": 0,
    "plusThreshold": 0
  },
  {
    "level": 1,
    "name": "Competitive Facility",
    "desc": "Sets the minimum Facilities Grade to D- with a maximum of D+. Adds 1 equipment slot.",
    "cost": 250,
    "renewCost": 50,
    "slotCap": 2,
    "bestGrade": "Dplus",
    "worstGrade": "Dminus",
    "normalThreshold": 50,
    "plusThreshold": 75
  },
  {
    "level": 2,
    "name": "Premier Facility",
    "desc": "Sets the minimum Facilities Grade to C- with a maximum of C+. Adds 1 equipment slot.",
    "cost": 500,
    "renewCost": 150,
    "slotCap": 3,
    "bestGrade": "Cplus",
    "worstGrade": "Cminus",
    "normalThreshold": 75,
    "plusThreshold": 150
  },
  {
    "level": 3,
    "name": "Elite Facility",
    "desc": "Sets the minimum Facilities Grade to B- with a maximum of B+. Adds 1 equipment slot.",
    "cost": 1500,
    "renewCost": 400,
    "slotCap": 4,
    "bestGrade": "Bplus",
    "worstGrade": "Bminus",
    "normalThreshold": 75,
    "plusThreshold": 150
  },
  {
    "level": 4,
    "name": "National Powerhouse",
    "desc": "Sets the minimum Facilities Grade to A- with a maximum of A+. Adds 1 equipment slot.",
    "cost": 3500,
    "renewCost": 750,
    "slotCap": 5,
    "bestGrade": "Aplus",
    "worstGrade": "Aminus",
    "normalThreshold": 150,
    "plusThreshold": 500
  }
];

export const FACILITY_EQUIPMENT: FacilityEquipment[] = [
  {
    "assetId": "10000000110001001100100101010100",
    "name": "Branded Equipment",
    "desc": "Increases Athletic Facility Grade and progression if below facility max. No effect on Basic Facility.",
    "cost": 100,
    "tier": 0,
    "effect": "Increase Athletic Facility Grade",
    "value": 50
  },
  {
    "assetId": "10000000110001001100100101010101",
    "name": "Trophy Room",
    "desc": "Increases Athletic Facility Grade and progression if below facility max. No effect on Basic Facility.",
    "cost": 200,
    "tier": 1,
    "effect": "Increase Athletic Facility Grade",
    "value": 75
  },
  {
    "assetId": "10000000110001001100100101010110",
    "name": "Player's Lounge",
    "desc": "Increases Athletic Facility Grade and progression if below facility max. No effect on Basic Facility.",
    "cost": 300,
    "tier": 2,
    "effect": "Increase Athletic Facility Grade",
    "value": 150
  },
  {
    "assetId": "10000000110001001100100101010111",
    "name": "Sports Science Lab",
    "desc": "Increases Athletic Facility Grade and progression if below facility max. No effect on Basic Facility.",
    "cost": 400,
    "tier": 3,
    "effect": "Increase Athletic Facility Grade",
    "value": 500
  },
  {
    "assetId": "10000000110100001011111101011001",
    "name": "Full Time Cleaning Staff",
    "desc": "Increases Equipment Lifespan.",
    "cost": 100,
    "tier": 0,
    "effect": "Increased Facility Longevity",
    "value": 20
  },
  {
    "assetId": "10000000110100001011111101011010",
    "name": "Repair Kits",
    "desc": "Increases Equipment Lifespan.",
    "cost": 250,
    "tier": 1,
    "effect": "Increased Facility Longevity",
    "value": 30
  },
  {
    "assetId": "10000000110100001011111101011011",
    "name": "Floor Mats",
    "desc": "Increases Equipment Lifespan.",
    "cost": 500,
    "tier": 2,
    "effect": "Increased Facility Longevity",
    "value": 40
  },
  {
    "assetId": "10000000110100001011111101011100",
    "name": "On-Demand Repairs",
    "desc": "Increases Equipment Lifespan.",
    "cost": 850,
    "tier": 3,
    "effect": "Increased Facility Longevity",
    "value": 50
  },
  {
    "assetId": "10000000110001001100100101000000",
    "name": "Training Table",
    "desc": "Reduces Injury Chance from practice and games.",
    "cost": 75,
    "tier": 0,
    "effect": "Reduce Injury Chance",
    "value": 15
  },
  {
    "assetId": "10000000110001001100100101000001",
    "name": "Massage Chairs",
    "desc": "Reduces Injury Chance from practice and games.",
    "cost": 225,
    "tier": 1,
    "effect": "Reduce Injury Chance",
    "value": 30
  },
  {
    "assetId": "10000000110001001100100101000010",
    "name": "Antigravity Treadmill",
    "desc": "Reduces Injury Chance from practice and games.",
    "cost": 400,
    "tier": 2,
    "effect": "Reduce Injury Chance",
    "value": 40
  },
  {
    "assetId": "10000000110001001100100101000011",
    "name": "Hyperbaric Chamber",
    "desc": "Reduces Injury Chance from practice and games.",
    "cost": 600,
    "tier": 3,
    "effect": "Reduce Injury Chance",
    "value": 50
  },
  {
    "assetId": "10000000110001001100100100101011",
    "name": "Organic Fruits",
    "desc": "Reduces Season Health Usage when Recovering.",
    "cost": 75,
    "tier": 0,
    "effect": "Reduce Season Health Usage",
    "value": 15
  },
  {
    "assetId": "10000000110001001100100100111101",
    "name": "Smoothie Bar",
    "desc": "Reduces Season Health Usage when Recovering.",
    "cost": 225,
    "tier": 1,
    "effect": "Reduce Season Health Usage",
    "value": 30
  },
  {
    "assetId": "10000000110001001100100100111110",
    "name": "Nutritionist",
    "desc": "Reduces Season Health Usage when Recovering.",
    "cost": 400,
    "tier": 2,
    "effect": "Reduce Season Health Usage",
    "value": 40
  },
  {
    "assetId": "10000000110001001100100100111111",
    "name": "Private Chef",
    "desc": "Reduces Season Health Usage when Recovering.",
    "cost": 600,
    "tier": 3,
    "effect": "Reduce Season Health Usage",
    "value": 50
  },
  {
    "assetId": "10000000110001001100100101001100",
    "name": "Ice Plunge",
    "desc": "Reduces Wear and Tear from practice and games.",
    "cost": 75,
    "tier": 0,
    "effect": "Reduce Wear and Tear",
    "value": 15
  },
  {
    "assetId": "10000000110001001100100101001101",
    "name": "Hydration Station",
    "desc": "Reduces Wear and Tear from practice and games.",
    "cost": 225,
    "tier": 1,
    "effect": "Reduce Wear and Tear",
    "value": 30
  },
  {
    "assetId": "10000000110001001100100101001110",
    "name": "Misting Fans",
    "desc": "Reduces Wear and Tear from practice and games.",
    "cost": 400,
    "tier": 2,
    "effect": "Reduce Wear and Tear",
    "value": 40
  },
  {
    "assetId": "10000000110001001100100101001111",
    "name": "Heart Rate Vests",
    "desc": "Reduces Wear and Tear from practice and games.",
    "cost": 600,
    "tier": 3,
    "effect": "Reduce Wear and Tear",
    "value": 50
  }
];

export function equipmentByAsset(assetId: string): FacilityEquipment | null {
  return FACILITY_EQUIPMENT.find((e) => e.assetId === assetId) ?? null;
}
