/**
 * The game's mental abilities: display name (+ description where the game
 * carries one), keyed by the save schema's MentalAbilities enum member —
 * the string madden-franchise reads from and writes to MentalAbility1..3.
 *
 * GENERATED by scripts/extract-mental-abilities.ts — do not edit by hand.
 *
 * Identifier drift is real (RoadFanFavorite shows as "Road Dog", DBRally as
 * "Legion", HotHead as "Rollercoaster"), so names come from the game's
 * tuning store, joined by enum value. source: 'game-display' = the exact
 * SignatureAbility.Name string; 'game-key' = the game's canonical ability
 * key split on case boundaries (no display row exists for it).
 */
export interface MentalAbilityDef {
  /** Name the game shows, e.g. "Road Dog" for RoadFanFavorite. */
  name: string;
  /** The game's own blurb for the ability, when it has one. */
  desc: string | null;
  source: 'game-display' | 'game-key';
}

export const MENTAL_ABILITIES: Record<string, MentalAbilityDef> = {
  Adrenaline: { name: "Adrenaline", desc: "Improves in-game recovery of wear and tear when off the field", source: "game-display" },
  BellCow: { name: "Bell Cow", desc: null, source: "game-key" },
  BestFriend: { name: "Best Friend", desc: "QB composure gain on first down receptions", source: "game-display" },
  Captain: { name: "Captain", desc: null, source: "game-key" },
  ClearHeaded: { name: "Clearheaded", desc: "Protection from composure loss", source: "game-display" },
  ClutchKicker: { name: "Clutch Kicker", desc: "Easier accuracy timing on late field goals", source: "game-display" },
  DBRally: { name: "Legion", desc: "Composure gain for all DBs on INT or PBU", source: "game-display" },
  DLRally: { name: "DL Rally", desc: "Tackles for loss increase the composure of other DL", source: "game-display" },
  FieldGeneral: { name: "Field General", desc: "Reveal key defenders", source: "game-display" },
  Headstrong: { name: "Headstrong", desc: "Resists hot routes being incorrect due to stadium pulse", source: "game-display" },
  HomeFanFavorite: { name: "Fan Favorite", desc: "Increased composure gains at home", source: "game-display" },
  HotHead: { name: "Rollercoaster", desc: "Composure gain and loss is more volatile", source: "game-display" },
  Instinct: { name: "Instinct", desc: "Quicker reaction to run plays", source: "game-display" },
  OLRally: { name: "OL Rally", desc: "Composure gain for OL on pancake blocks", source: "game-display" },
  Rhythm: { name: "Rhythm", desc: null, source: "game-key" },
  RoadFanFavorite: { name: "Road Dog", desc: "Increased composure gains on the road", source: "game-display" },
  TeamPlayer: { name: "Team Player", desc: "Improved ability to play out of position", source: "game-display" },
  TheNatural: { name: "The Natural", desc: "Improved resistance to weather impacts", source: "game-display" },
  Toughness: { name: "Toughness", desc: null, source: "game-key" },
  WinningTime: { name: "Winning Time", desc: "Increased composure late in close games", source: "game-display" },
};

/** Display name for a save-side mental-ability identifier (echoes unknowns). */
export function mentalAbilityName(id: string): string {
  return MENTAL_ABILITIES[id]?.name ?? id;
}
