/**
 * The game's own recruiting-pipeline and influence-tier names, keyed by the
 * save's Pipeline and PipelineInfluenceLevel enum members.
 *
 * GENERATED by scripts/extract-pipelines.ts — do not edit by hand.
 *
 * Names come from PipelineEnumTableEntry / PipelineInfluenceLevelEnumTableEntry
 * in the game's franchise-common tuning store (Field_3 = enum value, Field_1 =
 * display name, Field_0 = region blurb), joined through the save schema.
 */
export const PIPELINE_NAMES: Record<string, string> = {
  Alabama: "Alabama",
  Arizona: "Arizona",
  Arkansas: "Arkansas",
  BigApple: "Big Apple",
  BigSky: "Big Sky",
  CentralFlorida: "Central Florida",
  Colorado: "Colorado",
  EastTexas: "East Texas",
  Hawaii: "Hawaii",
  Illinois: "Illinois",
  Indiana: "Indiana",
  International: "National",
  Iowa: "Iowa",
  Kansas: "Kansas",
  Kentucky: "Kentucky",
  Louisiana: "Louisiana",
  MetroAtlanta: "Metro Atlanta",
  Michigan: "Michigan",
  Minnesota: "Minnesota",
  Mississippi: "Mississippi",
  Missouri: "Missouri",
  Nebraska: "Nebraska",
  Nevada: "Nevada",
  NewEngland: "New England",
  NewMexico: "New Mexico",
  NorthCarolina: "North Carolina",
  NorthFlorida: "North Florida",
  NorthTexas: "North Texas",
  NorthernCalifornia: "Northern California",
  Ohio: "Ohio",
  Oklahoma: "Oklahoma",
  PacificNorthwest: "Pacific Northwest",
  Pennsylvania: "Pennsylvania",
  SouthCarolina: "South Carolina",
  SouthFlorida: "South Florida",
  SouthGeorgia: "South Georgia",
  SouthernCalifornia: "Southern California",
  SouthwestTexas: "Southwest Texas",
  Tennessee: "Tennessee",
  Tidewater: "Tidewater",
  Utah: "Utah",
  WestVirginia: "West Virginia",
  Wisconsin: "Wisconsin",
};

/** Region blurb for pipelines whose name is not a place; absent means the name says it. */
export const PIPELINE_REGIONS: Record<string, string> = {
  BigApple: "New York and New Jersey",
  BigSky: "North Dakota, South Dakota, Wyoming, Montana, and Idaho",
  NewEngland: "Maine",
  PacificNorthwest: "Washington, Oregon, and Alaska",
  Tidewater: "Delaware, Maryland, and Virginia",
};

/** Influence tier names, lowest to highest by enum value. */
export const PIPELINE_LEVEL_NAMES: Record<string, string> = {
  Unrecognized: "Unrecognized",
  NicheInterest: "Niche Interest",
  Respected: "Respected",
  Popular: "Popular",
  HouseholdName: "Household Name",
  CulturalPillar: "Cultural Pillar",
};
