/**
 * The game's recruiting pitches: display name + the three motivations each
 * pitch is composed of, keyed by the save's IdealRecruitingPitch enum.
 *
 * GENERATED by scripts/extract-pitches.ts — do not edit by hand.
 *
 * Sourced from RecruitingPitchInfo / RecruitingPitchTypeEnumTableEntry /
 * RecruitingMotivationEnumTableEntry in the game's franchise-common tuning
 * store, joined through the save schema's own enum values. The motivation
 * order is the data order of RecruitingPitchInfo (Field_0/1/2); the on-screen
 * importance order has not been verified against the game UI.
 */
export interface PitchDef {
  /** Display name the game shows, e.g. "Gamer" for ItsGameTime. */
  name: string;
  /** The three motivations composing the pitch, in data order. */
  motivations: string[];
}

export const PITCHES: Record<string, PitchDef> = {
  Aspirational: { name: "Aspirational Goals", motivations: ["Championship Contender","Conference Prestige","Coach Prestige"] },
  CampusPersonality: { name: "Campus Personality", motivations: ["Campus Lifestyle","Playing Time","Playing Style"] },
  CoachsFavorite: { name: "Coach Connection", motivations: ["Athletic Facilities","Coach Prestige","Proximity To Home"] },
  CollegeExperience: { name: "College Experience", motivations: ["Academic Prestige","Campus Lifestyle","Stadium Atmosphere"] },
  ConferenceSpotlight: { name: "Conference Legend", motivations: ["Championship Contender","Conference Prestige","Proximity To Home"] },
  FootballInfluencer: { name: "Football Influencer", motivations: ["Brand Exposure","Playing Time","Pro Potential"] },
  Grassroots: { name: "Grassroots Traditionalist", motivations: ["Program Tradition","Proximity To Home","Stadium Atmosphere"] },
  HometownHero: { name: "Hometown Hero", motivations: ["Championship Contender","Program Tradition","Proximity To Home"] },
  ItsGameTime: { name: "Gamer", motivations: ["Conference Prestige","Playing Style","Pro Potential"] },
  Prestigious: { name: "Standard Bearer", motivations: ["Coach Prestige","Conference Prestige","Playing Style"] },
  ProveYourself: { name: "Status Seeker", motivations: ["Brand Exposure","Coach Prestige","Conference Prestige"] },
  Starter: { name: "Star Search", motivations: ["Brand Exposure","Playing Time","Proximity To Home"] },
  StudentOfTheGame: { name: "Student Of The Game", motivations: ["Academic Prestige","Coach Prestige","Proximity To Home"] },
  SundayBound: { name: "Sunday Player", motivations: ["Championship Contender","Conference Prestige","Pro Potential"] },
  TVTime: { name: "Primetime Player", motivations: ["Brand Exposure","Championship Contender","Playing Time"] },
  TeamPlayer: { name: "Team Player", motivations: ["Coach Stability","Playing Style","Proximity To Home"] },
  TheClutch: { name: "The Clutch", motivations: ["Coach Stability","Playing Style","Playing Time"] },
  TimeToGetToWork: { name: "Clocked In", motivations: ["Playing Style","Playing Time","Pro Potential"] },
  ToTheHouse: { name: "House Call", motivations: ["Brand Exposure","Coach Prestige","Championship Contender"] },
  WorkHorse: { name: "Gym Rat", motivations: ["Athletic Facilities","Brand Exposure","Pro Potential"] },
};
