/**
 * GENERATED by scripts/extract-playcall-art.ts — do not hand-edit.
 *
 * The game's play-concept catalog: display names and grouping from the
 * OffensivePlayConcepts / DefensivePlayConcepts enums in Core-Schemas,
 * joined to the playcall diagram art by normalized name. Each slug is a
 * gameicon://<slug> texture once extract-playcall-art.ts has run on the
 * machine; the UI hides entries whose art is absent.
 */

export interface PlayConcept {
  slug: string;
  name: string;
  group: string;
}

export const PLAY_CONCEPTS: PlayConcept[] = [
  {
    "slug": "pcc-run-counter",
    "name": "Counter",
    "group": "Run"
  },
  {
    "slug": "pcc-run-draw",
    "name": "Draw",
    "group": "Run"
  },
  {
    "slug": "pcc-run-insidezone",
    "name": "Inside Zone",
    "group": "Run"
  },
  {
    "slug": "pcc-run-iso",
    "name": "Iso",
    "group": "Run"
  },
  {
    "slug": "pcc-run-outsidezone",
    "name": "Outside Zone",
    "group": "Run"
  },
  {
    "slug": "pcc-run-power",
    "name": "Power",
    "group": "Run"
  },
  {
    "slug": "pcc-run-sweep",
    "name": "Sweep",
    "group": "Run"
  },
  {
    "slug": "pcc-run-trap",
    "name": "Trap",
    "group": "Run"
  },
  {
    "slug": "pcc-run-wham",
    "name": "Wham",
    "group": "Run"
  },
  {
    "slug": "pcc-run-endaround",
    "name": "End Around",
    "group": "Run"
  },
  {
    "slug": "pcc-run-reverse",
    "name": "Reverse",
    "group": "Run"
  },
  {
    "slug": "pcc-run-invertedveer",
    "name": "Inverted Veer",
    "group": "Option"
  },
  {
    "slug": "pcc-run-loadoption",
    "name": "Load Option",
    "group": "Option"
  },
  {
    "slug": "pcc-run-midlineoption",
    "name": "Midline Option",
    "group": "Option"
  },
  {
    "slug": "pcc-run-readoption",
    "name": "Read Option",
    "group": "Option"
  },
  {
    "slug": "pcc-run-shoveloption",
    "name": "Shovel Option",
    "group": "Option"
  },
  {
    "slug": "pcc-run-speedoption",
    "name": "Speed Option",
    "group": "Option"
  },
  {
    "slug": "pcc-run-tripleoption",
    "name": "Triple Option",
    "group": "Option"
  },
  {
    "slug": "pcc-run-zoneoption",
    "name": "Zone Option",
    "group": "Option"
  },
  {
    "slug": "pcc-pass-hitch",
    "name": "Hitch",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-ohio",
    "name": "Ohio",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-omaha",
    "name": "Omaha",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-scat",
    "name": "Scat",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-slants",
    "name": "Slant",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-spacing",
    "name": "Spacing",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-stick",
    "name": "Stick",
    "group": "Quick Pass"
  },
  {
    "slug": "pcc-pass-choice",
    "name": "Choice",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-curlflat",
    "name": "Curl",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-doublemove",
    "name": "Double Moves",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-drive",
    "name": "Drive",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-levels",
    "name": "Levels",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-mesh",
    "name": "Mesh",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-pivot",
    "name": "Pivot",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-salem",
    "name": "Salem",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-shake",
    "name": "Shake",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-shallowcross",
    "name": "Shallow Cross",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-slotcross",
    "name": "Slot Cross",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-smash",
    "name": "Smash",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-spot",
    "name": "Spot",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-texas",
    "name": "Texas",
    "group": "Medium Pass"
  },
  {
    "slug": "pcc-pass-comeback",
    "name": "Comeback",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-dagger",
    "name": "Dagger",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-divide",
    "name": "Divide",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-doubledig",
    "name": "Double Dig",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-doublepost",
    "name": "Double Post",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-flood",
    "name": "Flood",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-fourverticals",
    "name": "Four Verticals",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-go",
    "name": "Go",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-mills",
    "name": "Mills",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-portland",
    "name": "Portland",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-shot",
    "name": "Shot Play",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-switch",
    "name": "Switch",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-ycross",
    "name": "Y Cross",
    "group": "Deep Pass"
  },
  {
    "slug": "pcc-pass-boot",
    "name": "Boot",
    "group": "Play Action"
  },
  {
    "slug": "pcc-pass-slide",
    "name": "Slide",
    "group": "Play Action"
  },
  {
    "slug": "pcc-pass-bubblescreen",
    "name": "Bubble Screen",
    "group": "Screen"
  },
  {
    "slug": "pcc-pass-flscreen",
    "name": "FL SE Screen",
    "group": "Screen"
  },
  {
    "slug": "pcc-pass-hbslipscreen",
    "name": "HB Slip Screen",
    "group": "Screen"
  },
  {
    "slug": "pcc-pass-wrmidscreen",
    "name": "WR Mid Screen",
    "group": "Screen"
  },
  {
    "slug": "pcc-defense-blitz",
    "name": "Man Blitz",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-cover1",
    "name": "Cover 1",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-cover2",
    "name": "Cover 2",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-cover2man",
    "name": "Cover 2 Man",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-cover3",
    "name": "Cover 3",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-cover4",
    "name": "Cover 4",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-cover6",
    "name": "Cover 6",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-doubleman",
    "name": "Double Man",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-zoneblitz2deep",
    "name": "Zone Blitz 2 Deep",
    "group": "Defense"
  },
  {
    "slug": "pcc-defense-zoneblitz3deep",
    "name": "Zone Blitz 3 Deep",
    "group": "Defense"
  },
  {
    "slug": "pcc-rpo-rpo-read",
    "name": "RPO Read",
    "group": "RPO"
  },
  {
    "slug": "pcc-rpo-rpo-alert",
    "name": "RPO Alert",
    "group": "RPO"
  },
  {
    "slug": "pcc-rpo-rpo-peek",
    "name": "RPO Peek",
    "group": "RPO"
  }
];
