/**
 * GENERATED by scripts/extract-recruiting-tunables.ts — do not hand-edit.
 *
 * The game's recruiting rulebook constants, read from the RecruitingTunables
 * tuning-store row (indices mapped via the Core-Schemas XML). The per-prospect
 * weekly hour cap is a flat base — coach recruiter-tree perks add on top of
 * it via the save's CoachTalentEffects Recruiting_BonusHours slots.
 * Regenerate after game title updates:
 *   node --max-old-space-size=8192 scripts/extract-recruiting-tunables.ts
 */

export const RECRUITING_TUNABLES = {
  "maxHoursPerRecruitPerWeek": 50,
  "maxBoardTargets": 35,
  "maxTeamScholarshipOffers": 35,
  "maxRecruitVisitsPerWeek": 4,
  "maxTimesScouted": 5
} as const;
