/**
 * GENERATED by scripts/extract-recruiting-actions.ts — do not hand-edit.
 *
 * The game's weekly recruiting action hour costs, from RecruitingActionInfo
 * in the franchise-common tuning store (names joined via the action-type and
 * intensity enum tables). Hours are not freeform: each action costs a fixed
 * price, and a prospect's week is the sum of what you select.
 * Regenerate after game title updates:
 *   node --max-old-space-size=8192 scripts/extract-recruiting-actions.ts
 */

/** Hour cost of each weekly action, keyed by the app's action ids. */
export const ACTION_HOURS = {
  "contactFamily": 25,
  "contactCoaches": 10,
  "socialMedia": 5,
  "sendHouse": 50,
  "visitSchool": 40,
  "scoutFull": 10,
  "scholarship": 5,
  "softSell": 20,
  "hardSell": 40,
  "sway": 30
} as const;

/** The game's own display names — the save's field names have drifted:
 * ContactHighSchoolCoaches is really "DM the Player". */
export const ACTION_LABELS = {
  "contactFamily": "Contact Friends and Family",
  "contactCoaches": "DM the Player",
  "socialMedia": "Search Social Media",
  "sendHouse": "Send the House",
  "visitSchool": "Schedule Visit",
  "scoutFull": "Scouting"
} as const;

/** RecruitingActionType value -> the game's display name. */
export const ACTION_NAMES: Record<number, string> = {
  "0": "Spend Hours",
  "1": "Scouting",
  "2": "Pitch",
  "3": "Offer Scholarship",
  "4": "Schedule Visit",
  "5": "Search Social Media",
  "6": "DM the Player",
  "7": "Contact Friends and Family",
  "8": "Send the House",
  "9": "Send the House"
};
