/**
 * The game's scheme→archetype preferences: for every scheme, each position's
 * per-depth-slot preferred archetype and its importance weight — the data
 * behind the game's own depth-chart auto-fill and scheme fit.
 *
 * GENERATED by scripts/extract-scheme-fits.ts — do not edit by hand.
 *
 * Keyed by the save schema's BaseScheme identifiers (Team.Current*Scheme).
 * Slot order is the depth order (slot 0 = the starter), so the array length
 * is also the scheme's depth-chart window for that position. BaseScheme
 * value 0 (OFF_WEST_COAST_ZONE_RUN) has no data in the game store.
 */
export interface SchemeSlotPref {
  /** PlayerType enum member, same space as Player.PlayerType. */
  archetype: string;
  importance: number;
}

export const SCHEME_FITS: Record<string, Record<string, SchemeSlotPref[]>> = {
  DEF_3_2_6: {
    CB: [{ archetype: "CB_Zone", importance: 78 }, { archetype: "CB_Zone", importance: 72 }, { archetype: "CB_Slot", importance: 70 }, { archetype: "CB_Zone", importance: 50 }, { archetype: "CB_Zone", importance: 10 }],
    DT: [{ archetype: "DT_SpeedRusher", importance: 75 }, { archetype: "DT_SpeedRusher", importance: 25 }, { archetype: "DT_SpeedRusher", importance: 15 }],
    FS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 80 }, { archetype: "DE_RunStopper", importance: 16 }],
    LOLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    MLB: [{ archetype: "MLB_PassCoverage", importance: 25 }, { archetype: "MLB_PassCoverage", importance: 15 }, { archetype: "MLB_PassCoverage", importance: 10 }],
    RE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 16 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    SS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
  },
  DEF_3_3_5: {
    CB: [{ archetype: "CB_Zone", importance: 78 }, { archetype: "CB_Zone", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_Zone", importance: 16 }, { archetype: "CB_Zone", importance: 10 }],
    DT: [{ archetype: "DT_SpeedRusher", importance: 75 }, { archetype: "DT_SpeedRusher", importance: 25 }, { archetype: "DT_SpeedRusher", importance: 15 }],
    FS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 80 }, { archetype: "DE_RunStopper", importance: 16 }],
    LOLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    MLB: [{ archetype: "MLB_FieldGeneral", importance: 75 }, { archetype: "MLB_FieldGeneral", importance: 15 }, { archetype: "MLB_FieldGeneral", importance: 10 }],
    RE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 16 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    SS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
  },
  DEF_3_3_5_TITE: {
    CB: [{ archetype: "CB_Zone", importance: 78 }, { archetype: "CB_Zone", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_Zone", importance: 16 }, { archetype: "CB_Zone", importance: 10 }],
    DT: [{ archetype: "DT_SpeedRusher", importance: 75 }, { archetype: "DT_SpeedRusher", importance: 25 }, { archetype: "DT_SpeedRusher", importance: 15 }],
    FS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 80 }, { archetype: "DE_RunStopper", importance: 16 }],
    LOLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    MLB: [{ archetype: "MLB_FieldGeneral", importance: 75 }, { archetype: "MLB_FieldGeneral", importance: 15 }, { archetype: "MLB_FieldGeneral", importance: 10 }],
    RE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 16 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    SS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
  },
  DEF_3_4_MULTIPLE: {
    CB: [{ archetype: "CB_MantoMan", importance: 78 }, { archetype: "CB_MantoMan", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_MantoMan", importance: 16 }, { archetype: "CB_MantoMan", importance: 10 }],
    DT: [{ archetype: "DT_NoseTackle", importance: 75 }, { archetype: "DT_NoseTackle", importance: 15 }, { archetype: "DT_NoseTackle", importance: 10 }],
    FS: [{ archetype: "S_Zone", importance: 70 }, { archetype: "S_Zone", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 15 }],
    LOLB: [{ archetype: "OLB_PowerRusher", importance: 77 }, { archetype: "OLB_PowerRusher", importance: 16 }],
    MLB: [{ archetype: "MLB_PassCoverage", importance: 75 }, { archetype: "MLB_PassCoverage", importance: 65 }, { archetype: "MLB_PassCoverage", importance: 15 }],
    RE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 15 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 77 }, { archetype: "OLB_PassCoverage", importance: 16 }],
    SS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
  },
  DEF_4_2_5: {
    CB: [{ archetype: "CB_Zone", importance: 78 }, { archetype: "CB_Zone", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_Zone", importance: 16 }, { archetype: "CB_Zone", importance: 10 }],
    DT: [{ archetype: "DT_SpeedRusher", importance: 75 }, { archetype: "DT_SpeedRusher", importance: 26 }, { archetype: "DT_SpeedRusher", importance: 10 }],
    FS: [{ archetype: "S_Zone", importance: 70 }, { archetype: "S_Zone", importance: 15 }],
    LE: [{ archetype: "DE_SmallerSpeedRusher", importance: 78 }, { archetype: "DE_SmallerSpeedRusher", importance: 15 }],
    LOLB: [{ archetype: "OLB_PassCoverage", importance: 77 }, { archetype: "OLB_PassCoverage", importance: 16 }],
    MLB: [{ archetype: "MLB_FieldGeneral", importance: 25 }, { archetype: "MLB_FieldGeneral", importance: 65 }, { archetype: "MLB_FieldGeneral", importance: 15 }],
    RE: [{ archetype: "DE_SmallerSpeedRusher", importance: 78 }, { archetype: "DE_SmallerSpeedRusher", importance: 15 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 77 }, { archetype: "OLB_PassCoverage", importance: 16 }],
    SS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
  },
  DEF_4_3_MULTIPLE: {
    CB: [{ archetype: "CB_Zone", importance: 78 }, { archetype: "CB_Zone", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_Zone", importance: 16 }, { archetype: "CB_Zone", importance: 10 }],
    DT: [{ archetype: "DT_PowerRusher", importance: 75 }, { archetype: "DT_PowerRusher", importance: 65 }, { archetype: "DT_PowerRusher", importance: 15 }],
    FS: [{ archetype: "S_Zone", importance: 70 }, { archetype: "S_Zone", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 80 }, { archetype: "DE_RunStopper", importance: 16 }],
    LOLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    MLB: [{ archetype: "MLB_PassCoverage", importance: 75 }, { archetype: "MLB_PassCoverage", importance: 15 }, { archetype: "MLB_PassCoverage", importance: 10 }],
    RE: [{ archetype: "DE_SmallerSpeedRusher", importance: 78 }, { archetype: "DE_SmallerSpeedRusher", importance: 16 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    SS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
  },
  DEF_BASE3_4: {
    CB: [{ archetype: "CB_MantoMan", importance: 78 }, { archetype: "CB_MantoMan", importance: 72 }, { archetype: "CB_MantoMan", importance: 60 }, { archetype: "CB_MantoMan", importance: 16 }, { archetype: "CB_MantoMan", importance: 10 }],
    DT: [{ archetype: "DT_NoseTackle", importance: 75 }, { archetype: "DT_NoseTackle", importance: 15 }, { archetype: "DT_NoseTackle", importance: 10 }],
    FS: [{ archetype: "S_Zone", importance: 70 }, { archetype: "S_Zone", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 15 }],
    LOLB: [{ archetype: "OLB_PowerRusher", importance: 77 }, { archetype: "OLB_PowerRusher", importance: 16 }],
    MLB: [{ archetype: "MLB_FieldGeneral", importance: 75 }, { archetype: "MLB_FieldGeneral", importance: 65 }, { archetype: "MLB_FieldGeneral", importance: 15 }],
    RE: [{ archetype: "DE_RunStopper", importance: 78 }, { archetype: "DE_RunStopper", importance: 15 }],
    ROLB: [{ archetype: "OLB_PowerRusher", importance: 77 }, { archetype: "OLB_PowerRusher", importance: 16 }],
    SS: [{ archetype: "S_RunSupport", importance: 70 }, { archetype: "S_RunSupport", importance: 15 }],
  },
  DEF_BASE4_3: {
    CB: [{ archetype: "CB_MantoMan", importance: 78 }, { archetype: "CB_MantoMan", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_MantoMan", importance: 16 }, { archetype: "CB_MantoMan", importance: 10 }],
    DT: [{ archetype: "DT_NoseTackle", importance: 75 }, { archetype: "DT_NoseTackle", importance: 65 }, { archetype: "DT_NoseTackle", importance: 15 }],
    FS: [{ archetype: "S_Zone", importance: 70 }, { archetype: "S_Zone", importance: 15 }],
    LE: [{ archetype: "DE_RunStopper", importance: 80 }, { archetype: "DE_RunStopper", importance: 16 }],
    LOLB: [{ archetype: "OLB_RunStopper", importance: 72 }, { archetype: "OLB_RunStopper", importance: 15 }],
    MLB: [{ archetype: "MLB_FieldGeneral", importance: 75 }, { archetype: "MLB_FieldGeneral", importance: 15 }, { archetype: "MLB_FieldGeneral", importance: 10 }],
    RE: [{ archetype: "DE_SmallerSpeedRusher", importance: 78 }, { archetype: "DE_SmallerSpeedRusher", importance: 16 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    SS: [{ archetype: "S_RunSupport", importance: 70 }, { archetype: "S_RunSupport", importance: 15 }],
  },
  DEF_MULTIPLE_DEFENSE: {
    CB: [{ archetype: "CB_MantoMan", importance: 78 }, { archetype: "CB_Zone", importance: 72 }, { archetype: "CB_Slot", importance: 60 }, { archetype: "CB_MantoMan", importance: 16 }, { archetype: "CB_Zone", importance: 10 }],
    DT: [{ archetype: "DT_PowerRusher", importance: 75 }, { archetype: "DT_NoseTackle", importance: 65 }, { archetype: "DT_SpeedRusher", importance: 15 }],
    FS: [{ archetype: "S_Hybrid", importance: 70 }, { archetype: "S_Hybrid", importance: 15 }],
    LE: [{ archetype: "DE_PowerRusher", importance: 80 }, { archetype: "DE_RunStopper", importance: 16 }],
    LOLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    MLB: [{ archetype: "MLB_PassCoverage", importance: 75 }, { archetype: "MLB_FieldGeneral", importance: 15 }, { archetype: "MLB_PassCoverage", importance: 10 }],
    RE: [{ archetype: "DE_SmallerSpeedRusher", importance: 78 }, { archetype: "DE_SmallerSpeedRusher", importance: 16 }],
    ROLB: [{ archetype: "OLB_PassCoverage", importance: 72 }, { archetype: "OLB_PassCoverage", importance: 15 }],
    SS: [{ archetype: "S_Zone", importance: 70 }, { archetype: "S_Zone", importance: 15 }],
  },
  OFF_AIR_RAID: {
    C: [{ archetype: "C_PassProtector", importance: 76 }, { archetype: "C_PassProtector", importance: 15 }],
    FB: [{ archetype: "FB_Blocking", importance: 0 }],
    HB: [{ archetype: "HB_ElusivePower", importance: 70 }, { archetype: "HB_ReceivingBack", importance: 35 }, { archetype: "HB_ReceivingBack", importance: 15 }],
    LG: [{ archetype: "G_PassProtector", importance: 75 }, { archetype: "G_PassProtector", importance: 15 }],
    LT: [{ archetype: "OT_PassProtector", importance: 80 }, { archetype: "OT_PassProtector", importance: 17 }],
    QB: [{ archetype: "QB_Improviser", importance: 100 }, { archetype: "QB_Improviser", importance: 55 }, { archetype: "QB_Improviser", importance: 5 }],
    RG: [{ archetype: "G_PassProtector", importance: 75 }, { archetype: "G_PassProtector", importance: 15 }],
    RT: [{ archetype: "OT_Power", importance: 77 }, { archetype: "OT_Power", importance: 15 }],
    TE: [{ archetype: "TE_VerticalThreat", importance: 55 }, { archetype: "TE_Possession", importance: 16 }, { archetype: "TE_Possession", importance: 15 }],
    WR: [{ archetype: "WR_ShiftyRouteRunner", importance: 80 }, { archetype: "WR_Playmaker", importance: 75 }, { archetype: "WR_DeepThreat", importance: 70 }, { archetype: "WR_ShiftyRouteRunner", importance: 65 }, { archetype: "WR_Playmaker", importance: 55 }],
  },
  OFF_MULTIPLE_OFFENSE: {
    C: [{ archetype: "C_WellRounded", importance: 76 }, { archetype: "C_Power", importance: 15 }],
    FB: [{ archetype: "FB_Utility", importance: 0 }],
    HB: [{ archetype: "HB_ElusivePower", importance: 70 }, { archetype: "HB_ElusivePower", importance: 56 }, { archetype: "HB_PowerBack", importance: 15 }],
    LG: [{ archetype: "G_WellRounded", importance: 75 }, { archetype: "G_Power", importance: 15 }],
    LT: [{ archetype: "OT_WellRounded", importance: 80 }, { archetype: "OT_Power", importance: 17 }],
    QB: [{ archetype: "QB_Improviser", importance: 100 }, { archetype: "QB_Improviser", importance: 55 }, { archetype: "QB_Improviser", importance: 5 }],
    RG: [{ archetype: "G_WellRounded", importance: 75 }, { archetype: "G_Power", importance: 15 }],
    RT: [{ archetype: "OT_WellRounded", importance: 77 }, { archetype: "OT_Power", importance: 15 }],
    TE: [{ archetype: "TE_Possession", importance: 72 }, { archetype: "TE_Possession", importance: 16 }, { archetype: "TE_Possession", importance: 15 }],
    WR: [{ archetype: "WR_PhysicalRouteRunner", importance: 75 }, { archetype: "WR_ShiftyRouteRunner", importance: 68 }, { archetype: "WR_Playmaker", importance: 60 }, { archetype: "WR_Playmaker", importance: 16 }, { archetype: "WR_Playmaker", importance: 15 }],
  },
  OFF_OPTION: {
    C: [{ archetype: "C_Agile", importance: 76 }, { archetype: "C_Agile", importance: 15 }],
    FB: [{ archetype: "FB_Utility", importance: 56 }],
    HB: [{ archetype: "HB_PowerBack", importance: 70 }, { archetype: "HB_ElusiveBack", importance: 60 }, { archetype: "HB_PowerBack", importance: 50 }],
    LG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    LT: [{ archetype: "OT_Agile", importance: 80 }, { archetype: "OT_Agile", importance: 17 }],
    QB: [{ archetype: "QB_PureScrambler", importance: 100 }, { archetype: "QB_PureScrambler", importance: 55 }, { archetype: "QB_PureScrambler", importance: 5 }],
    RG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    RT: [{ archetype: "OT_Power", importance: 77 }, { archetype: "OT_Agile", importance: 15 }],
    TE: [{ archetype: "TE_Blocking", importance: 72 }, { archetype: "TE_Blocking", importance: 16 }, { archetype: "TE_Blocking", importance: 15 }],
    WR: [{ archetype: "WR_PhysicalBlocker", importance: 61 }, { archetype: "WR_PhysicalBlocker", importance: 55 }, { archetype: "WR_PhysicalBlocker", importance: 17 }, { archetype: "WR_PhysicalBlocker", importance: 16 }, { archetype: "WR_PhysicalBlocker", importance: 15 }],
  },
  OFF_PISTOL: {
    C: [{ archetype: "C_Agile", importance: 76 }, { archetype: "C_Agile", importance: 15 }],
    FB: [{ archetype: "FB_Blocking", importance: 40 }],
    HB: [{ archetype: "HB_PowerBack", importance: 70 }, { archetype: "HB_PowerBack", importance: 35 }, { archetype: "HB_PowerBack", importance: 15 }],
    LG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    LT: [{ archetype: "OT_Agile", importance: 80 }, { archetype: "OT_Agile", importance: 17 }],
    QB: [{ archetype: "QB_Scrambler", importance: 100 }, { archetype: "QB_Scrambler", importance: 55 }, { archetype: "QB_Scrambler", importance: 5 }],
    RG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    RT: [{ archetype: "OT_Agile", importance: 77 }, { archetype: "OT_Agile", importance: 15 }],
    TE: [{ archetype: "TE_Blocking", importance: 72 }, { archetype: "TE_Blocking", importance: 16 }, { archetype: "TE_Blocking", importance: 15 }],
    WR: [{ archetype: "WR_Physical", importance: 75 }, { archetype: "WR_Physical", importance: 68 }, { archetype: "WR_Playmaker", importance: 60 }, { archetype: "WR_Physical", importance: 16 }, { archetype: "WR_Physical", importance: 15 }],
  },
  OFF_POWER_SPREAD: {
    C: [{ archetype: "C_Agile", importance: 76 }, { archetype: "C_Agile", importance: 15 }],
    FB: [{ archetype: "FB_Blocking", importance: 0 }],
    HB: [{ archetype: "HB_ElusiveBack", importance: 70 }, { archetype: "HB_ElusiveBack", importance: 56 }, { archetype: "HB_ElusiveBack", importance: 15 }],
    LG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    LT: [{ archetype: "OT_Agile", importance: 80 }, { archetype: "OT_Agile", importance: 17 }],
    QB: [{ archetype: "QB_Scrambler", importance: 100 }, { archetype: "QB_Improviser", importance: 55 }, { archetype: "QB_Improviser", importance: 5 }],
    RG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    RT: [{ archetype: "OT_WellRounded", importance: 77 }, { archetype: "OT_Agile", importance: 15 }],
    TE: [{ archetype: "TE_Possession", importance: 72 }, { archetype: "TE_Possession", importance: 16 }, { archetype: "TE_Possession", importance: 15 }],
    WR: [{ archetype: "WR_Physical", importance: 75 }, { archetype: "WR_DeepThreat", importance: 68 }, { archetype: "WR_PhysicalBlocker", importance: 61 }, { archetype: "WR_Physical", importance: 60 }, { archetype: "WR_Physical", importance: 15 }],
  },
  OFF_PRO_STYLE: {
    C: [{ archetype: "C_Power", importance: 76 }, { archetype: "C_Power", importance: 15 }],
    FB: [{ archetype: "FB_Blocking", importance: 0 }],
    HB: [{ archetype: "HB_PowerBack", importance: 70 }, { archetype: "HB_PowerBack", importance: 35 }, { archetype: "HB_PowerBack", importance: 15 }],
    LG: [{ archetype: "G_Power", importance: 75 }, { archetype: "G_Power", importance: 15 }],
    LT: [{ archetype: "OT_PassProtector", importance: 80 }, { archetype: "OT_PassProtector", importance: 17 }],
    QB: [{ archetype: "QB_FieldGeneral", importance: 100 }, { archetype: "QB_FieldGeneral", importance: 55 }, { archetype: "QB_FieldGeneral", importance: 5 }],
    RG: [{ archetype: "G_Power", importance: 75 }, { archetype: "G_Power", importance: 15 }],
    RT: [{ archetype: "OT_PassProtector", importance: 77 }, { archetype: "OT_PassProtector", importance: 15 }],
    TE: [{ archetype: "TE_VerticalThreat", importance: 72 }, { archetype: "TE_VerticalThreat", importance: 16 }, { archetype: "TE_VerticalThreat", importance: 15 }],
    WR: [{ archetype: "WR_DeepThreat", importance: 75 }, { archetype: "WR_DeepThreat", importance: 68 }, { archetype: "WR_Playmaker", importance: 60 }, { archetype: "WR_DeepThreat", importance: 16 }, { archetype: "WR_DeepThreat", importance: 15 }],
  },
  OFF_RUN_AND_SHOOT: {
    C: [{ archetype: "C_PassProtector", importance: 76 }, { archetype: "C_PassProtector", importance: 15 }],
    FB: [{ archetype: "FB_Utility", importance: 0 }],
    HB: [{ archetype: "HB_ReceivingBack", importance: 70 }, { archetype: "HB_ReceivingBack", importance: 35 }, { archetype: "HB_ReceivingBack", importance: 15 }],
    LG: [{ archetype: "G_PassProtector", importance: 75 }, { archetype: "G_PassProtector", importance: 15 }],
    LT: [{ archetype: "OT_PassProtector", importance: 80 }, { archetype: "OT_PassProtector", importance: 17 }],
    QB: [{ archetype: "QB_Improviser", importance: 100 }, { archetype: "QB_FieldGeneral", importance: 55 }, { archetype: "QB_FieldGeneral", importance: 5 }],
    RG: [{ archetype: "G_PassProtector", importance: 75 }, { archetype: "G_PassProtector", importance: 15 }],
    RT: [{ archetype: "OT_PassProtector", importance: 77 }, { archetype: "OT_PassProtector", importance: 15 }],
    TE: [{ archetype: "TE_VerticalThreat", importance: 55 }, { archetype: "TE_VerticalThreat", importance: 16 }, { archetype: "TE_Possession", importance: 15 }],
    WR: [{ archetype: "WR_Playmaker", importance: 75 }, { archetype: "WR_ShiftyRouteRunner", importance: 70 }, { archetype: "WR_DeepThreat", importance: 65 }, { archetype: "WR_Playmaker", importance: 60 }, { archetype: "WR_ShiftyRouteRunner", importance: 56 }],
  },
  OFF_SPREAD: {
    C: [{ archetype: "C_Agile", importance: 76 }, { archetype: "C_Agile", importance: 15 }],
    FB: [{ archetype: "FB_Utility", importance: 0 }],
    HB: [{ archetype: "HB_ElusiveBack", importance: 70 }, { archetype: "HB_ElusiveBack", importance: 35 }, { archetype: "HB_ElusiveBack", importance: 15 }],
    LG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    LT: [{ archetype: "OT_PassProtector", importance: 80 }, { archetype: "OT_PassProtector", importance: 17 }],
    QB: [{ archetype: "QB_Improviser", importance: 100 }, { archetype: "QB_Improviser", importance: 55 }, { archetype: "QB_Scrambler", importance: 5 }],
    RG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    RT: [{ archetype: "OT_Agile", importance: 77 }, { archetype: "OT_Agile", importance: 15 }],
    TE: [{ archetype: "TE_VerticalThreat", importance: 72 }, { archetype: "TE_VerticalThreat", importance: 16 }, { archetype: "TE_VerticalThreat", importance: 15 }],
    WR: [{ archetype: "WR_DeepThreat", importance: 75 }, { archetype: "WR_Playmaker", importance: 68 }, { archetype: "WR_Playmaker", importance: 61 }, { archetype: "WR_Playmaker", importance: 60 }, { archetype: "WR_DeepThreat", importance: 54 }],
  },
  OFF_SPREAD_OPTION: {
    C: [{ archetype: "C_Agile", importance: 76 }, { archetype: "C_Agile", importance: 15 }],
    FB: [{ archetype: "FB_Utility", importance: 0 }],
    HB: [{ archetype: "HB_ElusiveBack", importance: 70 }, { archetype: "HB_ReceivingBack", importance: 35 }, { archetype: "HB_PowerBack", importance: 15 }],
    LG: [{ archetype: "G_Power", importance: 75 }, { archetype: "G_Power", importance: 15 }],
    LT: [{ archetype: "OT_PassProtector", importance: 80 }, { archetype: "OT_PassProtector", importance: 17 }],
    QB: [{ archetype: "QB_Scrambler", importance: 100 }, { archetype: "QB_Improviser", importance: 55 }, { archetype: "QB_Improviser", importance: 5 }],
    RG: [{ archetype: "G_Power", importance: 75 }, { archetype: "G_Power", importance: 15 }],
    RT: [{ archetype: "OT_Agile", importance: 77 }, { archetype: "OT_Agile", importance: 15 }],
    TE: [{ archetype: "TE_Blocking", importance: 55 }, { archetype: "TE_Blocking", importance: 16 }, { archetype: "TE_Blocking", importance: 15 }],
    WR: [{ archetype: "WR_Physical", importance: 75 }, { archetype: "WR_Playmaker", importance: 68 }, { archetype: "WR_Playmaker", importance: 60 }, { archetype: "WR_Playmaker", importance: 16 }, { archetype: "WR_Playmaker", importance: 15 }],
  },
  OFF_VEER_AND_SHOOT: {
    C: [{ archetype: "C_Agile", importance: 76 }, { archetype: "C_Agile", importance: 15 }],
    FB: [{ archetype: "FB_Blocking", importance: 0 }],
    HB: [{ archetype: "HB_ElusiveBack", importance: 70 }, { archetype: "HB_ReceivingBack", importance: 35 }, { archetype: "HB_ElusiveBack", importance: 15 }],
    LG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    LT: [{ archetype: "OT_PassProtector", importance: 80 }, { archetype: "OT_PassProtector", importance: 17 }],
    QB: [{ archetype: "QB_Improviser", importance: 100 }, { archetype: "QB_FieldGeneral", importance: 55 }, { archetype: "QB_FieldGeneral", importance: 5 }],
    RG: [{ archetype: "G_Agile", importance: 75 }, { archetype: "G_Agile", importance: 15 }],
    RT: [{ archetype: "OT_Agile", importance: 77 }, { archetype: "OT_Agile", importance: 15 }],
    TE: [{ archetype: "TE_VerticalThreat", importance: 60 }, { archetype: "TE_VerticalThreat", importance: 16 }, { archetype: "TE_VerticalThreat", importance: 15 }],
    WR: [{ archetype: "WR_DeepThreat", importance: 80 }, { archetype: "WR_Playmaker", importance: 75 }, { archetype: "WR_DeepThreat", importance: 70 }, { archetype: "WR_Playmaker", importance: 65 }, { archetype: "WR_DeepThreat", importance: 60 }],
  },
};

/**
 * How strongly a scheme wants this archetype at this position: the highest
 * importance across the depth slots naming it, 0 when the scheme never asks
 * for it (or the scheme/position is unknown).
 */
export function schemeFitImportance(scheme: string, position: string, archetype: string): number {
  const slots = SCHEME_FITS[scheme]?.[position];
  if (!slots) return 0;
  let best = 0;
  for (const s of slots) if (s.archetype === archetype && s.importance > best) best = s.importance;
  return best;
}
