/**
 * GENERATED by scripts/extract-talent-groups.ts — do not hand-edit.
 *
 * The coach talent position groups (CoachTalentPosGroup in the game's
 * Core-Schemas). The save's CoachTalentEffects bonus arrays — recruiter-perk
 * hours, scouting boosts — are 8-slot int[]s indexed by this enum, so a
 * perk's "condition" is the prospect's position group.
 * Regenerate after game title updates: node scripts/extract-talent-groups.ts
 */

/** slot value -> group name. */
export const POS_GROUP_NAMES: Record<number, string> = {
  "0": "QB",
  "1": "RB",
  "2": "WR_TE",
  "3": "OL",
  "4": "DB",
  "5": "LB",
  "6": "KP_ATH",
  "7": "LE_RE_DT"
};

/** save Position -> CoachTalentPosGroup slot. */
export const POSITION_TO_GROUP: Record<string, number> = {
  "QB": 0,
  "HB": 1,
  "FB": 1,
  "WR": 2,
  "TE": 2,
  "LT": 3,
  "LG": 3,
  "C": 3,
  "RG": 3,
  "RT": 3,
  "CB": 4,
  "FS": 4,
  "SS": 4,
  "LOLB": 5,
  "ROLB": 5,
  "MLB": 5,
  "K": 6,
  "P": 6,
  "ATH": 6,
  "LE": 7,
  "RE": 7,
  "DT": 7
};
