import { loadFranchise, mainTable, refFromRecord, val } from '../src/main/parser/franchise.ts';
const path = process.argv[2];
const fr = await loadFranchise(path);
const rT = mainTable(fr, 'Recruit');
await rT.readRecords();
const pT = mainTable(fr, 'Player');
await pT.readRecords();
const aaron = pT.records[refFromRecord(rT.records[4101], 'Player')!.row];
console.log(`before: ${val(aaron, 'PLYR_GENERICHEAD')} / ${val(aaron, 'GenericHeadAssetName')} / ${val(aaron, 'PLYR_PORTRAIT')}`);
(aaron as any).PLYR_GENERICHEAD = 'NoHead';
await (fr as any).save(path);
const check = await loadFranchise(path);
const pT2 = mainTable(check, 'Player');
await pT2.readRecords();
const a2 = pT2.records[refFromRecord(rT.records[4101], 'Player')!.row];
console.log(`after: ${val(a2, 'PLYR_GENERICHEAD')} / ${val(a2, 'GenericHeadAssetName')} / ${val(a2, 'PLYR_PORTRAIT')}`);
