/**
 * Generate src/shared/recruiting-tunables.ts — the game's recruiting rulebook
 * constants — from the franchise-common tuning store.
 *
 * The `RecruitingTunables` table (single row, 88 members) holds the live
 * values; the Core-Schemas XML (the 20MB FranTkData chunk) maps attribute
 * names to field indices, since the store reads with a generic schema:
 *   Field_34 = MaxTotalHoursOnRecruitPerWeek (the flat per-prospect weekly
 *              hour cap — coach recruiter perks add on top of it),
 *   Field_29 = MaxRecruitingBoardTargets, Field_32 = MaxTeamScholarshipOffers,
 *   Field_31 = MaxRecruitVisitsPerWeek, Field_33 = MaxTimesScouted.
 *
 * Verified anchors: hours cap 50, board targets 35. Run after title updates;
 * never hand-edit.
 *
 * Usage: node --max-old-space-size=8192 scripts/extract-recruiting-tunables.ts [--print]
 */
import * as mfModule from 'madden-franchise';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import zlib from 'node:zlib';
import {
  GAME_ROOT_DEFAULT,
  loadLayout,
  readTocPayload,
  parseSuperbundleToc,
  readRawCasBytes,
  decompressCasBlocksUnknownSize
} from './fb/frostbite.ts';

const mf: any = (mfModule as any).default ?? mfModule;
const OUT = 'src/shared/recruiting-tunables.ts';
const printOnly = process.argv.includes('--print');
process.on('unhandledRejection', () => {});

const layout = loadLayout(GAME_ROOT_DEFAULT);
const toc = parseSuperbundleToc(readTocPayload(path.join(layout.gameRoot, 'Data', 'Win32', 'globals.toc')));
const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'rtun-'));
let idx = 0;
let done = false;
for (const chunk of toc.chunks) {
  if (done) break;
  let payload: Buffer;
  try {
    payload = await decompressCasBlocksUnknownSize(layout, readRawCasBytes(layout, chunk.location));
  } catch {
    continue;
  }
  if (payload.length < 4 || payload[0] !== 0x78) continue;
  let image: Buffer;
  try {
    image = zlib.inflateSync(payload);
  } catch {
    continue;
  }
  if (image.subarray(0, 4).toString('latin1') !== 'FrTk') continue;
  if (!image.includes(Buffer.from('RecruitingTunables'))) continue;
  const tmp = path.join(tmpDir, `s${idx++}.ftc`);
  fs.writeFileSync(tmp, payload);
  let store: any;
  try {
    store = await (mf.create ?? mf.FranchiseFile?.create)(tmp);
  } catch {
    continue;
  }
  const t = (store.tables as any[]).find((x: any) => x.name === 'RecruitingTunables');
  if (!t) continue;
  try {
    await t.readRecords();
  } catch {
    continue;
  }
  const r0 = (t.records as any[]).find((r) => !r.isEmpty);
  if (!r0) continue;
  const num = (i: number): number => Number(r0._fields[`Field_${i}`]?.value ?? NaN);
  const RECRUITING_TUNABLES = {
    maxHoursPerRecruitPerWeek: num(34),
    maxBoardTargets: num(29),
    maxTeamScholarshipOffers: num(32),
    maxRecruitVisitsPerWeek: num(31),
    maxTimesScouted: num(33)
  };
  console.log('RECRUITING_TUNABLES:', JSON.stringify(RECRUITING_TUNABLES));
  if (RECRUITING_TUNABLES.maxHoursPerRecruitPerWeek !== 50 || RECRUITING_TUNABLES.maxBoardTargets !== 35) {
    throw new Error(`anchor failed: ${JSON.stringify(RECRUITING_TUNABLES)}`);
  }
  const banner = `/**
 * GENERATED by scripts/extract-recruiting-tunables.ts — do not hand-edit.
 *
 * The game's recruiting rulebook constants, read from the RecruitingTunables
 * tuning-store row (indices mapped via the Core-Schemas XML). The per-prospect
 * weekly hour cap is a flat base — coach recruiter-tree perks add on top of
 * it via the save's CoachTalentEffects Recruiting_BonusHours slots.
 * Regenerate after game title updates:
 *   node --max-old-space-size=8192 scripts/extract-recruiting-tunables.ts
 */
`;
  const body =
    banner +
    `\nexport const RECRUITING_TUNABLES = ${JSON.stringify(RECRUITING_TUNABLES, null, 2)} as const;\n`;
  if (printOnly) console.log(body);
  else {
    fs.writeFileSync(OUT, body.replace(/\r\n/g, '\n'));
    console.log(`wrote ${OUT}`);
  }
  done = true;
}
if (!done) throw new Error('RecruitingTunables not found');
