/**
 * Generate src/shared/talent-groups.ts — the coach talent position groups —
 * from the game's Core-Schemas XML (the 20MB FranTkData chunk in globals).
 *
 * Every coach talent targets a CoachTalentPosGroup, and the save's aggregated
 * CoachTalentEffects arrays (Recruiting_BonusHours, Recruiting_ScoutingBoost_
 * Start, …) are 8-slot int[]s indexed by exactly this enum: 0=QB 1=RB 2=WR_TE
 * 3=OL 4=DB 5=LB 6=KP_ATH 7=LE_RE_DT. That is the "condition" on recruiter
 * perks — they apply to prospects of the group's positions.
 *
 * The position expansion uses the save's own Position vocabulary; the anchor
 * asserts every recruiting position maps to a group.
 *
 * Usage: node scripts/extract-talent-groups.ts [--print]
 * Run after title updates; never hand-edit the output.
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  GAME_ROOT_DEFAULT,
  loadLayout,
  readTocPayload,
  parseSuperbundleToc,
  readRawCasBytes,
  decompressCasBlocksUnknownSize
} from './fb/frostbite.ts';

const OUT = 'src/shared/talent-groups.ts';
const printOnly = process.argv.includes('--print');

const layout = loadLayout(GAME_ROOT_DEFAULT);
const toc = parseSuperbundleToc(readTocPayload(path.join(layout.gameRoot, 'Data', 'Win32', 'globals.toc')));
let xml = '';
for (const chunk of toc.chunks) {
  if (!chunk.guid.startsWith('9b964b0c')) continue;
  const data = await decompressCasBlocksUnknownSize(layout, readRawCasBytes(layout, chunk.location));
  xml = data.toString('latin1');
  break;
}
if (!xml.includes('<FranTkData')) throw new Error('Core-Schemas chunk not found');

const at = xml.indexOf('<enum name="CoachTalentPosGroup"');
if (at < 0) throw new Error('CoachTalentPosGroup enum not found');
const block = xml.slice(at, xml.indexOf('</enum>', at));
const groups: Record<number, string> = {};
for (const m of block.matchAll(/<attribute name="([^"]+)" idx="\d+" value="(\d+)"/g)) {
  const value = Number(m[2]);
  const name = m[1];
  if (/^(First_|Last_|Max|Invalid|None|Count_)$/.test(name)) continue;
  if (!(value in groups)) groups[value] = name;
}
console.log('groups:', JSON.stringify(groups));
if (groups[0] !== 'QB' || groups[7] !== 'LE_RE_DT' || Object.keys(groups).length !== 8) {
  throw new Error(`anchor failed: ${JSON.stringify(groups)}`);
}

// The save's Position vocabulary, expanded onto the groups the enum names.
const POSITION_TO_GROUP: Record<string, number> = {
  QB: 0,
  HB: 1,
  FB: 1,
  WR: 2,
  TE: 2,
  LT: 3,
  LG: 3,
  C: 3,
  RG: 3,
  RT: 3,
  CB: 4,
  FS: 4,
  SS: 4,
  LOLB: 5,
  ROLB: 5,
  MLB: 5,
  K: 6,
  P: 6,
  ATH: 6,
  LE: 7,
  RE: 7,
  DT: 7
};

const banner = `/**
 * GENERATED by scripts/extract-talent-groups.ts — do not hand-edit.
 *
 * The coach talent position groups (CoachTalentPosGroup in the game's
 * Core-Schemas). The save's CoachTalentEffects bonus arrays — recruiter-perk
 * hours, scouting boosts — are 8-slot int[]s indexed by this enum, so a
 * perk's "condition" is the prospect's position group.
 * Regenerate after game title updates: node scripts/extract-talent-groups.ts
 */
`;
const body =
  banner +
  `\n/** slot value -> group name. */` +
  `\nexport const POS_GROUP_NAMES: Record<number, string> = ${JSON.stringify(groups, null, 2)};\n` +
  `\n/** save Position -> CoachTalentPosGroup slot. */` +
  `\nexport const POSITION_TO_GROUP: Record<string, number> = ${JSON.stringify(POSITION_TO_GROUP, null, 2)};\n`;
if (printOnly) console.log(body);
else {
  fs.writeFileSync(OUT, body.replace(/\r\n/g, '\n'));
  console.log(`wrote ${OUT}`);
}
